### PR TITLE
O3-1332:Results Viewer: Resizable Columns

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
I added a drag element in-between the columns to enable a user drag the column width to their desired width in a 'split' mode. While respecting some reasonable minWidth for each column.

## Screenshots

https://user-images.githubusercontent.com/33891016/193694301-0e6961ff-11a0-421b-851b-c3b6f23d6a8c.mp4

## Related Issue
https://issues.openmrs.org/browse/O3-1332 

## Other
Ref [PR](https://github.com/openmrs/openmrs-esm-patient-chart/pull/727)

### CODE REVIEW

**Comment by jwnasambu** [comment]
@vasharma05 , @ZacButko I believe the merge conflict is as a result of not pulling the changes as instructed prior. Kindly feel free to review my PR at your convinient time.

**Comment by vasharma05** [comment]
Thank you @jwnasambu for the work!

**Review by hadijahkyampeire — COMMENTED** [review]
@jwnasambu could you please resolve the merge conflicts, once they are resolved the PR should be good to be merged. Let me know if you need any assistance with that. Thanks for the great work on this.

**Comment by jwnasambu** [comment]
@hadijahkyampeire Thanks for the review.  I will surely do it.

**Pull request closed without merging**
