### PR TITLE
O3-3633 - Reusing the  visitable renderer for encounter and its obs without defining the components again

### PR DESCRIPTION
**Pull request by its-kios09**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

https://openmrs.atlassian.net/browse/O3-3633

## Screenshots

job

### CODE REVIEW

**Comment by ojwanganto** [comment]
Thanks, @its-kios09. 
Tagging @ibacher @denniskigen @brandones for their reviews

**Comment by ibacher** [comment]
Exporting something from an app and importing it into another app is always a programming error, because it couples two apps. If you want to reuse the component, extract it into the common library and use it from there.

**Comment by brandones** [comment]
It's really hard to tell what you're actually trying to accomplish, since all that's been written seems to be suggestions about how it should be implemented. Which anyway, as @ibacher indicated, isn't the right solution.

I would suggest adding this table to [esm-generic-patient-widgets-app](https://github.com/openmrs/openmrs-esm-patient-chart/tree/main/packages/esm-generic-patient-widgets-app). Then it can be added to dashboards as an extension and configured as needed. For reference, check out the existing extension, [`obs-by-encounter-widget`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/8f117b157710f4eee51c6684fdb28119d42a49d9/packages/esm-generic-patient-widgets-app/src/routes.json), and the details of its implementation.

**Comment by ojwanganto** [comment]
The guidance should be clear. Thanks, @ibacher @brandones.
@its-kios09 please take note.

**Pull request closed without merging**
