### PR TITLE
O3-1635: Test results viewer: Search in panel view

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR brings the search functionality in the Test results viewer's Panel view. Below are the screenshots of the different views.

## Screenshots

image
image
image
image
image
image
image

## Related Issue
https://issues.openmrs.org/browse/O3-1635

### CODE REVIEW

**Comment by ibacher** [comment]
Wouldn't it make sense to include live, filtered results in the Tablet view as you do on the desktop view?

**Comment by vasharma05** [comment]
Hi @ibacher !
Thanks for asking.

As per the designs [here](https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/622223a8e732c558cf9c3ce9), the search will open up in an overlay in the tablet view. It'll also include the recent searches in the overlay, as per the designs.
I am working on storing the recent searches now.
Thanks!

**Comment by vasharma05** [comment]
I believe, since it's the tablet view, it has small screen size, and hence, we can think to move ahead with this.

If you insist. I can start a thread to clear the doubts.
Thanks!

**Review by FlorianRappl — APPROVED** [review]
LGTM - great work!

**Comment by vasharma05** [comment]
Thank you @ibacher and @FlorianRappl!

@ibacher, for the conclusion in the slack thread, if there's a change in the design, I'll make a new ticket and work on it separately. Merging this PR for the time being.

Thanks!

**Pull request merged**
