### PR TITLE
(chore) Release `v5.0.0`

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.
## Summary

Patient Chart `v5.0.0` is a `major` release that includes performance improvements plus a host of new features and bug fixes.

Being a `major` release, `v5.0.0` introduces a breaking change. We recommend reading the [Core v5 migration guide](https://o3-docs.vercel.app/docs/migration-guide) to understand the rationale behind this breaking change and its impact on your application.

### Performance improvements

We have migrated all the frontend modules in Patient Chart to leverage the new module loading mechanism introduced in [Core v5](https://github.com/openmrs/openmrs-esm-core/releases/tag/v5.0.0). Frontend modules now declare their static and dynamic metadata upfront, and the framework uses this information to load only the static bits when the application gets loaded for the first time while loading the dynamic bits is deferred to later when they are needed. This change delivers significant improvements to initial load time. Check out the [migration guide](https://o3-docs.vercel.app/docs/migration-guide) to get a closer look at the internals of the new module loading mechanism.

### Translation support for the left nav menu

`v5.0.0` adds support for internationalising dashboard titles in the left nav. Each dashboard can specify a `title` string property that represents the dashboard's name. This `title` then gets passed to the `DashboardExtension` component which invokes the `t` function from the `useTranslation` hook, passing in the `title`. To round things off, the frontend module's `moduleName` gets passed as the `namespace` argument of `useTranslation`, letting it know where to look for the corresponding translations.  This mechanism makes it easy to translate your dashboard names.

### Migrating React forms to use RHF and Zod for schema validation

`v5.0.0` ushers in React Hook Forms (RHF) for handling forms. RHF is a performant forms solution that reduces the boilerplate code you need to write when constructing forms. RHF is also performant and supports a host of schema validation solutions. Zod is a schema validation library that integrates well with RHF and TypeScript. RHF's simple API and Zod’s declarative schema approach make your code easier to read and maintain. RHF and Zod present a robust approach to handling forms in React. `v5.0.0` ports the `Conditions` and `Visit notes` forms to use RHF and Zod, with more custom React forms in the pipeline.

### Initial support for patient flags and improved RDE capabilities

This release establishes the groundwork for patient flags and improved RDE capabilities. Patient flags are visual components that enable healthcare providers to see relevant patient information with a glance in the Patient chart. `v5.0.0` also adds improved retrospective data entry capabilities to the Patient Chart. Both patient flags and RDE improvements are a work in progress, and we will be adding more features to them in subsequent releases.

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]

**Comment by denniskigen** [comment]
Thanks for approving @vasharma05, please don't merge yet.

**Comment by gracepotma** [comment]
Re. "Migrating React forms to use RHF and Zod for schema validation" - @denniskigen is the key point here that this replaces Formik? IIRC we were concerned about that dependency.

**Comment by denniskigen** [comment]
That's correct, Grace. Ultimately, we want to port forms that use Formik and Yup (notable examples are the registration form and the form preview in the React form engine) to RHF and Zod. Also, we want to move the existing React-based forms (such as programs, conditions, visit notes, etc) to use RHF and Zod for the benefits mentioned in the highlights section.

**Comment by ibacher** [comment]
@denniskigen We should update the peerDependency of esm-patient-common-lib to `5.x` in the various modules too.

**Comment by denniskigen** [comment]
Done. Thanks for the reminder, @ibacher.

**Review by ibacher — APPROVED** [review]

**Pull request merged**
