### PR TITLE
(Improvement: 03-1856): Appointments cancel modal improvements.

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
- Better naming of the appointments cancel modal action buttons texts.

## Screenshots
- 
Screenshot 2023-02-10 at 18 45 29

## Related Issue
- [Better naming of the Appointments cancel modal.](https://issues.openmrs.org/browse/O3-1856)

### CODE REVIEW

**Comment by ibacher** [comment]
Can these be separated into a PR-per-ticket? I know they're small things, but we should be committing at the level of features, meaning each PR should (ideally) fix one thing.

**Comment by ibacher** [comment]
PS for the condition thing: instead of messing with the CSS of disabled text (which is going to be hard to get exactly right), why not just render a fixed label if we're editing and skip the search component altogether?

**Comment by hadijahkyampeire** [comment]
@ibacher I have removed the `conditions` changes I will do them in a seperate PR.

**Review by vasharma05 — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
