### PR TITLE
O3-4025: Add an icon for patient summary on the left nav

### PR DESCRIPTION
**Pull request by shishiro26**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number. Ensure the title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label (e.g., `fix:`, `feat:`, `chore:`).  
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).  
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR addresses the addition of an icon to the left sidebar in the `esm-patient-chart-app`.

## Screenshots

image

## Related Issue

Jira Ticket: [O3-4025](https://openmrs.atlassian.net/jira/software/c/projects/O3/issues/O3-4025)

## Other Information

[O3-4025]: https://openmrs.atlassian.net/browse/O3-4025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by shishiro26** [comment]
@VeronicaMuthee, could you please review this PR?

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @shishiro26 , is it possible to make this configurable ? Instead of hardcoding the icon ?

**Comment by denniskigen** [comment]
@paulsonder @ciaranduffy do we have any mockups for this?

**Comment by dkayiwa** [comment]
> Could you please clarify what you mean by making it 'configurable'? I'm not sure if I fully understand.

https://o3-docs.openmrs.org/docs/configuration-system

**Comment by ciaranduffy** [comment]
Hi @denniskigen, we don't use icons in the RefApp designs. However, if an implementation really wants to use icons, we would recommend using the default Carbon Design left nav item component, with the icon variation. [You can see that documented here](https://carbondesignsystem.com/components/UI-shell-left-panel/code/). 

The screenshot above doesn't look like it's using the default carbon left nav component as the icon doesn't look correctly aligned.

**Comment by shishiro26** [comment]
> The screenshot above doesn't look like it's using the default carbon left nav component as the icon doesn't look correctly aligned.

Hi @ciaranduffy  I took the design from the documentation shared in the ticket ([Google Docs](https://docs.google.com/presentation/d/1Ks5A3npsKX0PV-ulZvCIeSwP-um8tA4ULCH-rVWiSOQ/edit#slide=id.p)), as it was mentioned there.

>we would recommend using the default Carbon Design left nav item component, with the icon variation. [You can see that documented here](https://carbondesignsystem.com/components/UI-shell-left-panel/code/).

yes sir there was a mistake from my side I will update the icon with the carbon react-icons and remove the hardcoded icons

**Pull request closed without merging**
