### PR TITLE
(chore) Extract translations from extension, hook and workspace files 

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR looks into the missing places where the translation support is missing, or the translations strings are not extracted well.

### Before
image

### After
image

## Related Issue
https://issues.openmrs.org/browse/O3-4253

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]
Code LGTM. Do you know why tests are failing?

**Comment by denniskigen** [comment]
Any clue why this is failing, @ibacher? Could it be something similar to core? This is the one where the siderail doesn't load.

**Comment by ibacher** [comment]
Can't be similar to the issue in core. For all the other e2e tests, we actually just basically use [everything in the workspace](https://github.com/openmrs/openmrs-esm-patient-chart/blob/edc522b3e6a4f35eca237390861f75c51be1193f/e2e/support/github/run-e2e-docker-env.sh#L8), so that one is auto-generated.

**Comment by ibacher** [comment]
Do we need to update the framework? It looks like we're using the `WorkspaceContainer` from there and this repo is about a week behind, which means it's missing @vasharma05's latest workspace refactor... Although I believe it started failing before that?

**Comment by denniskigen** [comment]
On it

**Comment by denniskigen** [comment]
Didn't work.

**Comment by ibacher** [comment]
It's still missing the side rail, but it's also missing the set of tests in the result viewer. I can't see why those would be connected...

**Pull request merged**
