### PR TITLE
(feat) Remove implementer-specific logic from Programs widget

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR removes some implementer-specific configurations from the Programs widget.

## Screenshots
*None*

## Related Issue
*None*

## Other
*None*

### CODE REVIEW

**Review by denniskigen — DISMISSED** [review]
Looks ok to me.

**Comment by donaldkibet** [comment]
ping @CynthiaKamau @makombe this is to be moved to in house package

**Review by ibacher — APPROVED** [review]
LGTM

**Comment by ibacher** [comment]
@donaldkibet Is there some way we could make this easier to move to the in-house package? I.e., we know implementations will need specific logic and we'd prefer that that doesn't get built by creating too many custom components if it's something we can build with standard components—this is part of the goal of O3 is to not fragment into a thousand different page implementations if we can.

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
