### PR TITLE
(chore) Bump RFE version for QA

### PR DESCRIPTION
**Pull request by pirupius**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary
Bumps RFE for QA

### CODE REVIEW

**Comment by denniskigen** [comment]
Per this trace, it looks like there's an issue with submitting the edited form. Maybe try and submit the actual form with the test values to see whether you can replicate on dev3.

CleanShot 2024-11-15 at 12  19 26@2x

**Comment by pirupius** [comment]
Thanks @denniskigen for flagging this.

**Comment by denniskigen** [comment]
@samuelmale any idea why this is failing, Sam?

**Comment by samuelmale** [comment]
So the issue was introduced by this [PR](https://github.com/openmrs/openmrs-esm-form-engine-lib/pull/421) and the error is propagating from [this specific line](https://github.com/openmrs/openmrs-esm-form-engine-lib/blob/main/src/processors/encounter/encounter-processor-helper.ts#L58). 

@usamaidrsk did you intended to map over a fields collection instead of the obs array?

**Review by samuelmale — APPROVED** [review]

**Pull request merged**
