### PR TITLE
(feat) Use patient-chart-app namespace for patient-common-lib translations

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
Currently, the translations for the common lib are not registered, since the common lib doesn't export translations.
Current workarounds are to comment add translations in all the apps the common components is imported into.
Now the translations for all the common components will be mapped to the `@openmrs/esm-patient-chart-app` namespace.

**The main changes in this PR resides in the very first commit. Other changes are just cleanup**

P.S. The reason for a very large number of files is the change in the translation files.

## Screenshots
image

### CODE REVIEW

**Comment by vasharma05** [comment]
I'm sorry @ibacher , let me update it to proper title.

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Could you fix the failing unit test and update this to the latest `main`? The e2e tests should pass then.

**Comment by vasharma05** [comment]
This wasn't supposed to happen🤨 How did I miss this. 

No worries @ibacher , I'll look into it

**Comment by ibacher** [comment]
Updating to `main` apparently fixed things... Hopefully we don't also have a flaky unit test...

**Pull request merged**
