### PR TITLE
Trend and Timeline unresponsive in Tablet mode 

### PR DESCRIPTION
**Pull request by Eriq-Kibet**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

- Makes Trend an Timeline responsive in tablet mode.

## Screenshots

Trend and timeline responsive

## Issue

- Issue  [O3-856](https://issues.openmrs.org/browse/O3-856?filter=-1)

### CODE REVIEW

**Comment by brandones** [comment]
It looks like exactly the same thing is returned whether `isTablet` is true or false. What are you trying to do?

**Comment by Eriq-Kibet** [comment]
> It looks like exactly the same thing is returned whether `isTablet` is true or false. What are you trying to do?

I wrapped `Overview` and `OverflowBorder` in one `OverflowBorder` to display the trend and Timeline below the Card in Tablet mode.

**Comment by brandones** [comment]
Oh I see, thanks. And the way it's structured in tablet mode now doesn't also work in desktop mode?

**Comment by Eriq-Kibet** [comment]
> Oh I see, thanks. And the way it's structured in tablet mode now doesn't also work in desktop mode?



In tablet mode Trend and timeline display on the right side and are very small.  
Screenshot from 2021-11-08 14-23-06
When the dimensions get smaller they don't display at all
No trend and timeline

**Comment by brandones** [comment]
Right, again, what I'm asking is: does the way that you have implemented it for tablet mode also work in desktop mode?

**Comment by Eriq-Kibet** [comment]
> Right, again, what I'm asking is: does the way that you have implemented it for tablet mode also work in desktop mode?

Yes

**Comment by brandones** [comment]
Okay, so let's get rid of the special code for desktop mode, and just use the tablet mode code for everything.

**Comment by brandones** [comment]
@Eriq-Kibet messaged me to the effect that, in fact, the code for tablet mode does *not* also work for desktop mode.

Let's refactor this a little bit so that we're not duplicating big blocks of code. You can create new components, tiny little components defined within this same file (but do not define components within other components).

**Comment by Eriq-Kibet** [comment]
> @Eriq-Kibet messaged me to the effect that, in fact, the code for tablet mode does _not_ also work for desktop mode.
> 
> Let's refactor this a little bit so that we're not duplicating big blocks of code. You can create new components, tiny little components defined within this same file (but do not define components within other components).

Okay

**Pull request closed without merging**
