### PR TITLE
03-1627: Attachements upload modal should be able to close

### PR DESCRIPTION
**Pull request by kdaud**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary

The close button on the attachment modal isn't working 
## Screenshots

[attachment.webm](https://user-images.githubusercontent.com/38831673/206453331-7e9c2570-fade-494b-9b89-c2e5f0bb6906.webm)

## Related Issue

https://issues.openmrs.org/browse/O3-1627

### CODE REVIEW

**Comment by vasharma05** [comment]
The file changes looks good to me, I'll do a quick run on my local machine before moving ahead.
Thanks a lot @kdaud with the work!

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @kdaud, code looks perfect and the attached recording shows that it works well but for some reason when I checked out your PR to test locally it didn't work, it could be an issue with some cache maybe 🤔

**Comment by vasharma05** [comment]
Hi @hadijahkyampeire , I tested it on my local system, it's working and the code looks fine too.
Merging the PR

**Review by vasharma05 — APPROVED** [review]
Nice catch!
Thanks for the same!

**Pull request merged**
