### PR TITLE
(feat) O3-4166 - add option to hide links in vitals header

### PR DESCRIPTION
**Pull request by chibongho**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

https://openmrs.atlassian.net/browse/O3-4166

We have a use case to include the vitals header in the ward app, and have it not display any links to the O3 patient chart or launch the record vitals workspace. 

I thought about adding a config option in the vitals app to configure custom links and use `<ConfigurableLink>`, but that doesn't let us represent `launchWorkspace` actions.

### CODE REVIEW

**Review by donaldkibet — APPROVED** [review]
Thanks @chibongho LGTM

**Review by denniskigen — COMMENTED** [review]
LGTM. Could we add some test coverage for the new case?

**Comment by denniskigen** [comment]
I’ll have a look. Thanks, @chibongho!

**Comment by denniskigen** [comment]
Apparently, it's because that button text matches two elements:

CleanShot 2024-11-07 at 12  49 07@2x

Using a regex match should get it to match the exact text:

```tsx
expect(screen.getByRole('button', { name: /^record vitals$/i })).toBeInTheDocument();
```

**Pull request merged**
