### PR TITLE
O3-2891: Refactor Patient Appointments ESM into Appointments ESM

### PR DESCRIPTION
**Pull request by mogoodrich**
This basically removed the entire patient-appointments ESM, needs to merged in with it's partner PR that adds this functionality to the appointments app in the patient management monorepo, see:

https://openmrs.atlassian.net/browse/O3-2891

## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Review by chibongho — APPROVED** [review]
LGTM. (That was easy...)

**Review by ojwanganto — APPROVED** [review]

**Review by denniskigen — APPROVED** [review]
Thanks, @mogoodrich!

**Comment by mogoodrich** [comment]
Thanks @chibongho  @ojwanganto  and @denniskigen .... the checks appear to be hung so I may close and reopen to try to resolve and then push the new  PR through without review... :)

**Comment by mogoodrich** [comment]
Fixed a couple things I missed that were causing errors, merging this in now, thanks all!

**Pull request merged**
