### PR TITLE
(fix) O3-3547: Handle possibly undefined encounter.obs in LabResultsForm

### PR DESCRIPTION
**Pull request by PiusKariuki**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR fixes an issue in the `LabResultsForm` component where clicking the `Add results` button from the `OrderDetails` table overflow menu would sometimes fail to successfully launch the form. 

To remedy this, I've tweaked the logic so that the code that sets `obsUuid` and `isEditing` is in a useEffect hook. This ensures that we only try to access `encounter.obs`when it is available and not undefined. I've also moved the logic for fetching initial values into a separate useEffect hook that depends on `isEditing` and `obsUuid`.

## Screenshots

- This is a recording of the issue
[patient-orders-result-error.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/39379012/a4301643-28a4-4dc3-8914-297d9df55cab)

- This is the recording after the fix
[fix-add-results.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/39379012/2e0aafbc-7832-4119-83c7-6af3893b7ea6)

## Related Issue
[LINK TO JIRA TICKET](https://openmrs.atlassian.net/browse/O3-3547)

### CODE REVIEW

**Comment by PiusKariuki** [comment]
@brandones Please help me review this PR.

**Comment by pirupius** [comment]
Thanks @PiusKariuki for this. Did you test this with lab sets?

**Comment by PiusKariuki** [comment]
Yes I did. I used a list of lab tests

**Review by pirupius — COMMENTED** [review]
Is there work that hasn't been committed yet? The video recording in your PR description shows it's working but i've pulled your branch and it has the same error


Screenshot 2024-07-09 at 08 43 25

https://github.com/openmrs/openmrs-esm-patient-chart/assets/15266028/7340d8fe-3bc6-4cdc-8161-1ec3c5d90b9d

**Comment by PiusKariuki** [comment]
@pirupius I have not experienced this behaviour let me test it again then I'll ping you on slack

**Review by ibacher — APPROVED** [review]

**Review by CynthiaKamau — APPROVED** [review]

**Pull request merged**
