### PR TITLE
(chore) Bump `esm-form-entry-app` to Angular v14

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Necessitated by https://github.com/openmrs/openmrs-ngx-formentry/pull/88.

This PR updates Angular to v14. Additionally, I've:

- Replaced `@angular-architects/module-federation` with a version of [ngx-build-plus](https://www.npmjs.com/package/ngx-build-plus) that is compatible with Angular v14. I've also updated our custom webpack config, replacing the deprecated `contentBase` property of the `devServer` config and adding a `scriptType` property with the value `text/javascript` (which fixes this issue with the webpack build output not matching the structure of an O3 federated module).
- Replaced the [ngx-file-uploader-openmrs] dependency with [@openmrs/ngx-file-uploader](https://www.npmjs.com/package/@openmrs/ngx-file-uploader) after I recently migrated the source repository to the OpenMRS [GitHub organization](https://github.com/openmrs/openmrs-ngx-file-uploader).
- Bumped several Angular test-related dependencies.
- Fix some Carbon-related type annotations (unrelated to the form entry app).
- Fix some breaking tests (not sure what led to the test failures; they don't seem to fail on `main`).

Relates to https://github.com/openmrs/openmrs-ngx-formentry/pull/89.

## Screenshots

> Forms rendering with Angular 14

CleanShot 2023-10-14 at 5  05 18@2x

### CODE REVIEW

**Review by ibacher — APPROVED** [review]

**Comment by denniskigen** [comment]
Any tips for how to fix the failing conditions spec here, @jayasanka-sack?

**Comment by jayasanka-sack** [comment]
It seems it's having trouble with clicking the kebab menu button. I will look into this further and get back to you.
Screenshot 2023-10-15 at 15 27 02

**Review by vasharma05 — DISMISSED** [review]
Looks good to me!

**Review by vasharma05 — APPROVED** [review]
Looks good to me!!!

**Review by vasharma05 — APPROVED** [review]

**Pull request merged**
