### PR TITLE
(chore) Release v7.2.0

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR cuts a new minor release of Patient Chart.

### CODE REVIEW

**Review by NethmiRodrigo — APPROVED** [review]
LGTM! Thanks @denniskigen!

**Comment by ibacher** [comment]
Wait!

**Comment by ibacher** [comment]
This needs to be 8.0.0 because of the breaking changes in the common lib.

**Comment by denniskigen** [comment]
Which ones, @ibacher?

Here's the draft changelog:

### New features

* (feat) O3-2647: Add ability to add lab results and view within orders widget by @pirupius in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1731
* (feat) Only show diagnoses concepts in visit notes diagnosis search by @nanfuka in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1742
* (feat) Reuse upcoming appointment work to mark appointments as `Checked In` by @donaldkibet in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1743
* (feat) Disable encounter date field when pre-filled by @icrc-jofrancisco in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1747
* (feat) O3-2627: Remove leading dot from allowedExtensions MIME types config by @icrc-loliveira in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1780
* (feat) O3-3084: Sort fetched tests alphabetically in the lab order search inside order basket by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1797
* (feat) O3-3077: Add validation to restrict users from initiating future visit by @donaldkibet in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1793
* (feat) O3-1422 / O3-2724: Move workspace system into the framework by @brandones in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1796
* (feat) Update Angular form engine translations by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1801
* (feat) O3-3112: Add form collapse toggle to the `esm-form-engine-app` by @usamaidrsk in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1814
* (feat) O3-3133: Adapt cancel logic in the react form engine workspace by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1816
* (feat) O3 3128: Add extension slots to lab and drug order forms by @donaldkibet in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1818
* (feat) O3-2626: Add useAllowedFileExtensions hook to Common Lib by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1824
* (feat) O3-3156: Submitting the start visit form should mutate appointments by @mogoodrich in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1825
* (feat) O3-3158: Conditionally render Patient Header in the Start Visit form by @mogoodrich in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1823

### Refactors

* (refactor) O3-2831: Move patient banner into styleguide by @brandones in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1645
* (refactor) Refactor move patient to next queue in visit header to ali… by @makombe in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1735
* (refactor) Remove duplicate type from SingleSpaProps type annotation by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1760
* (refactor) Update PatientProgram interface to display program workflows and states by @CynthiaKamau in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1820
* (refactor) O3-2626: Reuse useAllowedFileExtensions hook from Common Lib by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1827
* (refactor) O3-2891: Refactor Patient Appointments ESM into Appointments ESM by @mogoodrich in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1739

### Bug fixes

* (fix) 03-2959: Update E2E tests for clinical forms workspace by @chimanwadike in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1732
* (fix) O3-2969: Vitals table doesn't display warnings for abnormal values after the first page by @mccarthyaaron in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1738
* (fix) Various fixes for the visit notes form by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1744
* (fix) O3-2977: Make end date field editable for inactive conditions by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1750
* (fix) O3-2978: Update E2E test steps for attachment workflow by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1758
* (fix) O3-2627: Improvements to the visit notes image upload functionality by @jwnasambu in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1748
* (fix) O3-2937: Make clinical status mandatory in the conditions form by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1757
* (fix) O3-2657: Show inline errors when saving orders fails by @usamaidrsk in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1667
* (fix) O3-2604: Add a “refresh data“ button to the test results viewer by @jwnasambu in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1671
* (fix) O3-3046: Allow sorting by date in vitals and biometrics table by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1775
* (fix) O3-2813 disable test type edit when modifying lab orders by @pirupius in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1782
* (fix) O3-3046: Updated the interpretation keys for vital signs matching table headers by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1791
* (fix) O3-2975: Encounter datetime should not be sent when saving vitals and biometrics form by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1790
* (fix) O3-3093: React form engine workspace should close after submitting a form by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1804
* (fix) Use order reasons should correctly chunk concept references and  load all of them by @ibacher in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1813
* (fix) O3-3133: Clicking the cancel button should not close the workspace by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1815
* (fix) O3-2852: Fix the viewport size of the Start Visit form on tablet  by @Madhu-mac in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1765
* (fix) O3-3158: Follow-up commit fixing patientUuid sometimes undefined by @ibacher in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1831
* (fix) O3-3196: Fix diagnoses tags display on tablet by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1834
* (fix) O3-3195: Fix rendering logic for the weight tile by @jona42-ui in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1835
* (fix) Return encounter type uuid from encounter type object by @arodidev in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1836
* (fix) O3-3046: Allow sorting vitals, biometrics and conditions rows based on different sort functions by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1779
* (fix) O3-2717: Form workspace shrinks when opened while on the Vitals & Biometrics page by @mccarthyaaron in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1745

### Housekeeping

* (chore) Bump @openmrs/ngx-formentry by @icrc-loliveira in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1740
* (chore) Bump follow-redirects from 1.15.5 to 1.15.6 by @dependabot in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1736
* (chore) Bump webpack-dev-middleware from 5.3.3 to 5.3.4 by @dependabot in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1753
* (chore) Bump @openmrs/ngx-formentry by @icrc-loliveira in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1752
* (chore) Bump @openmrs/ngx-formentry by @icrc-jofrancisco in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1769
* (chore) Separate linting and formatting concerns by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1774
* (chore) Update translations from Transifex by @github-actions in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1707
* (chore) Bump playwright by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1781
* (chore) Add Eslint Rule to validate exhaustive deps on React hooks by @hadijahkyampeire in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1773
* (chore) Flag rules-of-hooks lint violations by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1784
* (chore) Update translations from Transifex by @github-actions in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1776
* (chore) Bump @openmrs/ngx-formentry by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1788
* (chore) Bump @openmrs/esm-form-engine-app by @CynthiaKamau in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1789
* (chore) Remove orders widget feature flag by @pirupius in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1787
* (chore) Bump Angular form engine by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1799
* (chore) Bump `@openmrs/esm-form-engine-lib` by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1807
* (chore) Bump @openmrs/openmrs-form-engine-lib by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1808
* (chore) O3-3114: Bump react form engine by @CynthiaKamau in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1809
* (chore) clean up unused webpack config and bumps engine by @pirupius in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1810
* (chore) Bump form-engine with added translations by @vasharma05 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1811
* (chore) Bump react form engine by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1817
* (chore) Bump ejs from 3.1.9 to 3.1.10 by @dependabot in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1819
* (chore) Bump playwright by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1822
* (chore) Bump form-engine lib by @samuelmale in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1828
* (chore) Bump form-engine lib by @samuelmale in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1829
* (chore) Bump RFE version by @arodidev in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1833
* (chore) Bump React form engine and yarn by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1837
* (chore) Bump express from 4.18.1 to 4.19.2 by @dependabot in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1759
* (chore) Bump tar from 6.1.12 to 6.2.1 by @dependabot in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1786

### Docs

* (docs) O3-2891: Refactor Patient Appointments ESM docs from Patient chart by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1746
* (docs) O3-2416: Move E2E docs from the README to the O3 docs testing guide by @piyushmishra1416 in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1770

### Tests

* (test) O3-2943: Add e2e test for the immunization recording workflow by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1728
* (test) O3-2939: Explicitly break down E2E tests steps in patient-chart  to mimic user experience by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1721
* (test) O3-2978: Add E2E test for attachments workflow by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1749
* (test) O3-3000: Add E2E tests for editing and deleting an allergy by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1761
* (test) 03-2947: Add an E2E test for the test results viewer by @chimanwadike in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1737
* (test) Remove mock implementations of usePagination by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1777
* (test) O3-3040: Add E2E test for adding a visit note by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1783
* (test) O3-3040: Add delete test case in the visit note workflow by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1785
* (test) Refactor lab orders E2E test by @denniskigen in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1803
* (test) Split lab test step for saving the form by @kdaud in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1805

**Comment by ibacher** [comment]
It's this one:

* (feat) O3-1422 / O3-2724: Move workspace system into the framework by @brandones in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1796

That removes a couple of function exports. It's sort of technically a `feat` if you assume that the patient-common-lib is only used in the patient-chart (which is the intention) because the same commit also changes the relevant code in the chart, but it does break things for down-stream things like ohri-commons-lib.

**Comment by denniskigen** [comment]
Thanks, Ian. I'll go ahead and mark it as a breaking change so it's clear.

**Comment by denniskigen** [comment]
Closing in favour of https://github.com/openmrs/openmrs-esm-patient-chart/pull/1839

**Pull request closed without merging**
