### PR TITLE
(feat) add ability to use ohri-form engine on patient chart

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Add ability to launch and use the `OHRI` form engine. I have also made it configurable to retain the current implementation where we are using the `AMPATH` form engine.

Only to be merged once https://github.com/UCSF-IGHS/openmrs-ohri-form-engine-lib/pull/86 has been merged. @samuelmale @denniskigen @ibacher @gracepotma what are your thought on this?

## Screenshots
ohri-form

## TODO
- Better error handling
- Edit mode
- Fix error while saving

### CODE REVIEW

**Comment by ibacher** [comment]
I like this for the most part; however:

1. I'd prefer that the workspace embedding the OHRI form engine be moved to it's own app, rather than integrated into the patient-forms-app
2. I'd prefer that the workspace embedding the OHRI form engine not use an extension. This feels like an abuse of the extension system since we're expecting one and only one type of thing to be rendered there.

Ideally, we'd have a single workspace, called `patient-form-entry-workspace` and an implementation could either chose to use the AMPATH form engine (which would then render in that workspace) or use the OHRI form engine (which would then render in that same workspace). This would basically remove the need for any configuration other than what's declared in the import map (and we can add an error if an implementation somehow ends up with two workspaces with the same registration, similar to what we do with extensions).

**Comment by donaldkibet** [comment]
> I like this for the most part; however:
> 
> 1. I'd prefer that the workspace embedding the OHRI form engine be moved to it's own app, rather than integrated into the patient-forms-app
> 2. I'd prefer that the workspace embedding the OHRI form engine not use an extension. This feels like an abuse of the extension system since we're expecting one and only one type of thing to be rendered there.
> 
> Ideally, we'd have a single workspace, called `patient-form-entry-workspace` and an implementation could either chose to use the AMPATH form engine (which would then render in that workspace) or use the OHRI form engine (which would then render in that same workspace). This would basically remove the need for any configuration other than what's declared in the import map (and we can add an error if an implementation somehow ends up with two workspaces with the same registration, similar to what we do with extensions).

Alright make sense. In that regard am closing this PR.

**Comment by samuelmale** [comment]
Thank you for starting this, Donald! There is a plan to develop an app that dispenses OHRI forms within the RefApp. I was hoping to start working on this next week. Donald, would you like to collaborate with me to make sure we don't duplicate efforts?

**Comment by donaldkibet** [comment]
> Thank you for starting this, Donald! There is a plan to develop an app that dispenses OHRI forms within the RefApp. I was hoping to start working on this next week. Donald, would you like to collaborate with me to make sure we don't duplicate efforts?

Sure

**Pull request closed without merging**
