### PR TITLE
O3-2630: "no-wrap" being applied to all TDs in the O3 app?

### PR DESCRIPTION
**Pull request by mogoodrich**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by mogoodrich** [comment]
See https://openmrs.atlassian.net/browse/O3-2630  this. removes the global no-wrap, but assumedly someone will want to fix this to add back in the expected behavior in the paginated vitals app.

**Comment by vasharma05** [comment]
I believe we should move this override with more specific/ better solution to esm-styleguide, other than having it in the vitals app.

Thanks @mogoodrich for the PR!

**Comment by vasharma05** [comment]
Please resolve the merge conflicts!

**Review by vasharma05 — APPROVED** [review]

**Comment by ibacher** [comment]
A better solution here would be to change the rule from `td` to a classname and then ensure the `td` in the vitals app uses that classname. That will keep things for the vitals app, unbreak the rest of the world, and stop the addition of weird global rules.

**Comment by mogoodrich** [comment]
Agree @ibacher ... I was hoping someone with familiarity with the vitals app could fix this and apply it only where needed...   I will wait a bit and see if anyone steps up.... is there a right person to work on this @vasharma05 ?  @Jexsie ? otherwise, I would just remove and leave whoever cares about the vitals app to fix, as this is a breaking, global change...

**Comment by vasharma05** [comment]
I'll look into it, no worries, should be a work for a few minutes only. Thanks @mogoodrich @ibacher

**Comment by mogoodrich** [comment]
Great, thanks @vasharma05 !

**Comment by denniskigen** [comment]
Looks like I beat you to it, @vasharma05 https://github.com/openmrs/openmrs-esm-patient-chart/pull/1544 😉

**Pull request closed without merging**
