### PR TITLE
(fix) O3-904: Datatable sorting controls should sort the entire dataset

### PR DESCRIPTION
**Pull request by nanfuka**
## Requirements

- [x] This PR has a title that briefly describes

 the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This pull request addresses the issue where sorting a column in a biometrics tables with multiple pages of results only sorts items within the current page. The solution ensures that sorting a column now sorts the entire dataset.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-chart/assets/29108523/9bd0d5eb-0089-4dca-8b55-b382f13fcfec

## Related Issue

https://issues.openmrs.org/browse/O3-904

### CODE REVIEW

**Comment by nanfuka** [comment]
@brandones kindly review

**Comment by brandones** [comment]
Nice, thanks @nanfuka ! Can you tell me a bit about the logic for loading data? Does it download all biometrics data at once, or does it only download what is needed to view the current page? In the latter case, what happens if I haven't gone to any later pages before sorting?

**Comment by nanfuka** [comment]
I have used `useSWRInfinite` for data loading, which follows an infinite loading pattern. This means that it doesn't download all biometric data at once. Instead, it loads data as needed for the current page and, optionally, preloads data for adjacent pages.

Initially, when you access a specific page, `useSWRInfinite` fetches data for that page and then preloads data for subsequent pages. For instance, if you're on page 1, it can fetch data for page 2, and so on. This preloading mechanism ensures that when you navigate to the next page, the data is already available without the need for additional network requests.

**Comment by brandones** [comment]
Right, okay, so what happens if I'm on page 1, and I don't navigate to any other page, and then I hit the sort button?

**Pull request closed without merging**
