### PR TITLE
(test)O3-2401: Fix test for visit-form.component.tsx after new migration to RHF

### PR DESCRIPTION
**Pull request by ayush-AI**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
In this PR I have added some tests which got ommitted due to failures during the migration to RHF after fixing them.

## Related Issue
[O3-2401](https://issues.openmrs.org/browse/O3-2401)

### CODE REVIEW

**Comment by ayush-AI** [comment]
cc/ @hadijahkyampeire @lumuchris256 @vasharma05 @jayasanka-sack

**Comment by jayasanka-sack** [comment]
@ayush-AI Is this ready to be merged?

**Comment by ayush-AI** [comment]
> @ayush-AI Is this ready to be merged?

Not yet @jayasanka-sack need to add some more test cases which @vasharma05 suggested.

**Comment by ayush-AI** [comment]
I have added the new tests for visit-form component which checks for the different scenarios of the visitAttribute fields. Please check.
cc:/ @lumuchris256 @vasharma05 @hadijahkyampeire @jayasanka-sack

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @ayush-AI

**Pull request merged**
