### PR TITLE
(feat) Add ability to conditionally show visit attributes

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR allows showing visit attribute types conditionally based on JavaScript expressions defined in the configuration schema. It adds an `evaluateExpression` function which is invoked when a visitAttributeType has a `showWhenExpression` property.  This function splits the expression into its constituent parts and ultimately runs it and returns the result of its evaluation. If the expression is truthy, then the visit attribute gets rendered. If the expression is falsy, then the visit attribute does not get rendered.

If the visitAttributeType does not have a `showWhenExpression` defined property, the condition short-circuits to true and it gets rendered by default.

With this approach, the conditionally rendered visit attributes get included in the payload when the user submits the form.

Sample config:

```tsx
{
  "@openmrs/esm-patient-chart-app": {
    "visitAttributeTypes": [
      {
        "uuid": "caf2124f-00a9-4620-a250-efd8535afd6d"
      },
      {
        "uuid": "c39b684c-250f-4781-a157-d6ad7353bc90",
        "showWhenExpression": "visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === '1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf'"
      },
      {
        "uuid": "2d0fa959-6780-41f1-85b1-402045935068",
        "showWhenExpression": "visitAttributes['c39b684c-250f-4781-a157-d6ad7353bc90'] === '159356AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' && visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === '1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf'"
      },
      {
        "uuid": "0f4f3306-f01b-43c6-af5b-fdb60015cb02",
        "showWhenExpression": "visitAttributes['c39b684c-250f-4781-a157-d6ad7353bc90'] === '159356AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' && visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === '1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf'"
      },
      {
        "uuid": "50e6a142-89fd-437d-a071-48434f850e43",
        "showWhenExpression": "visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === 'c844c73e-75e0-4020-98d1-739af20a6f63'"
      }
    ]
  }
}
```

## Screenshots
https://github.com/openmrs/openmrs-esm-patient-chart/assets/28008754/ea11dd7c-3551-44c1-a286-a529f78409bc

### CODE REVIEW

**Review by CynthiaKamau — APPROVED** [review]

**Comment by vasharma05** [comment]
Do test the edit visit details flow before merging the PR.
Thanks!

**Comment by ibacher** [comment]
@donaldkibet I don't see how `evaluateExpression` works for the more complex logic in your example cases, e.g.,

```js
visitAttributes['c39b684c-250f-4781-a157-d6ad7353bc90'] === '159356AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' && visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === '1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf'
```

This works:

```js
visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d'] === '1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf'
```

Because:

```js
const [left, operator, right] = expression.split(' ');
```

Gives:

```js
const left = 'visitAttributes['caf2124f-00a9-4620-a250-efd8535afd6d']' ;
const op = '===';
const right = '\'1c30ee58-82d4-4ea4-a8c1-4bf2f9dfc8cf\''
```

But for the more complex situation, it will only evaluate the first criteria.

**Comment by ibacher** [comment]
I'd probably suggest something like:

```ts
function evaluateExpression(expression: string, visitAttributes: VisitAttributes) {
  const func = new Function(['visitAttributes'], 'return ' + expression);
  let result: unknown = func.call(null, visitAttributes);
  return Boolean(result);
}
```

**Comment by ibacher** [comment]
Right. The proper solution here is something like a parser like [jsep](https://ericsmekens.github.io/jsep/) and a AST-walker that ensures that strictly limits what gets executed, but that's basically a mini-JS interpreter; the above is, for better or worse, essentially the code we already run for expressions in the form engines.

**Comment by denniskigen** [comment]
I agree. And it's likely not something we have the bandwidth to build for this one usecase. What do you recommend we do in the interim, @ibacher.

**Pull request merged**
