### PR TITLE
(test) Add E2E test for editing existing visits

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR adds an E2E test for editing existing visits in O3. It also renames the Start visit E2E test for clarity. This test covers the following scenarios:

- Navigating to the Visits summary page
- Launching the "Edit Visit" form
- Verifying the presence and state of form elements
- Modifying visit details (changing visit type from "Facility Visit" to "Home Visit")
- Submitting the form
- Verifying the presence of a success notification
- Checking that the updated visit details are displayed correctly in both the Visit tile and the Active Visit tag in the Patient Header.

One thing that's not adequately covered is the ability to change the visit location (which is what [originally informed](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1955) this work). How can I populate the dropdown with additional locations in the test environment @jayasanka-sack @kdaud?

### CODE REVIEW

**Review by kdaud — APPROVED** [review]
LGTM

**Comment by kdaud** [comment]
> How can I populate the dropdown with additional locations in the test environment @jayasanka-sack @kdaud?

I'm not sure about this. @jayasanka-sack might have some ideas.

**Comment by kdaud** [comment]
@denniskigen I tested the scenario and found that clearing the current location populates the dropdown list, letting you choose any option.
```  
await page.getByRole('combobox', { name: 'Select a location' }).clear();
```

**Comment by denniskigen** [comment]
Excellent, thanks @kdaud. I've pushed an update doing exactly that.

**Review by kdaud — APPROVED** [review]

**Comment by kdaud** [comment]
Thanks @denniskigen

**Pull request merged**
