### PR TITLE
(refactor) O3-2815: Replace usages of `/ws/rest/v1` with `restBaseUrl`

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Change all instances of the hard-coded API base URL '/ws/rest/v1/' to use the restBaseUrl variable instead. To enhances maintainability and flexibility of the API base URL configuration.

## Screenshots
None

## Related Issue
https://openmrs.atlassian.net/browse/O3-2815

### CODE REVIEW

**Comment by usamaidrsk** [comment]
Thanks @jwnasambu for the initiative.
Looking at the value `restBaseUrl` resolves to, I think it's about replacing `'/ws/rest/v1/'`  with `restBaseUrl`

cc @denniskigen

**Comment by jwnasambu** [comment]
@usamaidrsk Thanks so much! @denis was clear with the ticket description its me on the wrong and am trying to fix my errors.

**Comment by jwnasambu** [comment]
@denniskigen, @usamaidrsk, @ibacher kindly how can I go about with the E2E Tests build faller. Basing on the research I have done, Am  getting The error you're encountering (SyntaxError: Unexpected token 'export') suggests that the environment in which you're running your code doesn't support ECMAScript module syntax.

To resolve this, you can try the following steps:

Ensure Node.js Version:
Make sure you are using a version of Node.js that supports ECMAScript modules (ESM). Node.js versions 13.2.0 and later support ESM. You can check your Node.js version using: node --version` Apparently am running node -v  
v18.12.0 which shouldn't be the cause.

**Comment by ibacher** [comment]
Do not change the strings in mocks or test files at all. Only in the production code. Also, in one place, a regular expression was changed to remove the preceding `.+`, which makes that code non-functional.

**Comment by vasharma05** [comment]
```
yarn up @openmrs/esm-framework@next openmrs@next
```

**Comment by denniskigen** [comment]
Thanks, @jwnasambu!

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
