### PR TITLE
(chore) Reuse built artifacts in pre-release and release jobs

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR modifies the `release` and `pre-release` jobs to reuse artifacts from the `build` job. Presently, these jobs don't always run successfully. This is most often due to the CI running out of memory. Reusing built artifacts obviates the need to redo the expensive build step.

### CODE REVIEW

**Review by brandones — APPROVED** [review]
If that's all it takes—awesome!

**Comment by denniskigen** [comment]
> If that's all it takes—awesome!

I haven't tested it out yet. Seems `lerna version` doesn't provide a way to do a dry run. 

Any ideas on how to test this out?

**Comment by brandones** [comment]
`lerna version` doesn't push any changes anywhere. The thing that pushes changes is [`lerna publish`](https://github.com/openmrs/openmrs-esm-patient-chart/blob/bd8f963fbf3f69583dc719a31990ef24d79c631d/package.json#L11).

So you could test this by commenting out the lines

```
run: yarn run ci:prepublish
```

and

```
if: ${{ github.event_name == 'push' }}
```

**Comment by denniskigen** [comment]
What do you reckon, @brandones https://github.com/openmrs/openmrs-esm-patient-chart/runs/6394331231?check_suite_focus=true?

**Comment by brandones** [comment]
Sorry for the silence—are those built artifacts the ones we expect?

```
Artifact 0a8ab8eaf152c6c5 was downloaded to /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/0a8ab8eaf152c6c5
Artifact 0c808d6953e2e77c was downloaded to /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/0c808d6953e2e77c
Artifact 118bfd5ef4fd0df3 was downloaded to /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/118bfd5ef4fd0df3
Artifact packages was downloaded to /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/packages
```

Seems a little funny—I would expect JS files.

**Comment by ZacButko** [comment]
@denniskigen will explore this some more in the future.

**Pull request closed without merging**
