### PR TITLE
(feat) Change allergy `Onset date and comments` to `Onset comments`

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Change the label for `Onset date and comments' to `Onset comments` to avoid indicating that the date is also captured on the control

### CODE REVIEW

**Review by jayasanka-sack — COMMENTED** [review]
Hello, @donaldkibet, I appreciate your pull request. As far as my understanding goes, the modification to include both the 'onset date' and 'comments' in a single field was a deliberate decision. This alteration enables users to input the onset date for an allergy within the comments section. The rationale behind this approach is that having a separate field for the onset date posed challenges. For instance, some patients may not be certain of the exact onset date, while others may only provide an estimate. By combining the onset date with the comments field, we aim to offer flexibility to users. 

@gracepotma , could you kindly confirm?

**Comment by donaldkibet** [comment]
cc @CynthiaKamau @makombe @ojwanganto

**Comment by ojwanganto** [comment]
@jayasanka-sack while it is OK to document both onset date and any comment in the control, users have expressed confusion as to whether there should be a date control or not. Their interpretation of the label is that the control has erroneously been missed. I support @donaldkibet in changing the label and I further propose that we update the placeholder text in the control to take care of an onset date, if available, and any comments

**Comment by jayasanka-sack** [comment]
P.S. Here's a screenshot from the updated allergy form https://github.com/openmrs/openmrs-esm-patient-chart/pull/1525: 

image

**Comment by CynthiaKamau** [comment]
> Hello, @donaldkibet, I appreciate your pull request. As far as my understanding goes, the modification to include both the 'onset date' and 'comments' in a single field was a deliberate decision. This alteration enables users to input the onset date for an allergy within the comments section. The rationale behind this approach is that having a separate field for the onset date posed challenges. For instance, some patients may not be certain of the exact onset date, while others may only provide an estimate. By combining the onset date with the comments field, we aim to offer flexibility to users.
> 
> @gracepotma , could you kindly confirm?

The model does not have the onset date field, only date_created.

**Review by jayasanka-sack — CHANGES_REQUESTED** [review]
Hi @donaldkibet , 

Could you please change `onset comments` to just `Comments`?

**Comment by brandones** [comment]
Closing as stale.

**Comment by brandones** [comment]
There is also no ticket for this change, and it would be a significant UI change.

**Pull request closed without merging**
