### PR TITLE
Adaptations to the context workspace (Enable closing from within / Enable scrolling)

### PR DESCRIPTION
**Pull request by manuelroemer**
* Pass callbacks to the hosted context workspace content to enable closing the workspace from within
* Enable scrolling inside the workspace

### CODE REVIEW

**Comment by FlorianRappl** [comment]
The build fails here. There are some errors with the dependencies. Most likely we need to rebuild the package-lock.

**Comment by manuelroemer** [comment]
Should work now. I also had to add "esnext" to the tsconfig, otherwise the build would not work locally.

**Comment by FlorianRappl** [comment]
Yeah I think we should remove these usages in 3.0.9 - I've noted them down.

**Review by FlorianRappl — APPROVED** [review]
LGTM - thanks :beers:!

**Pull request merged**
