### PR TITLE
Switch from useCurrentPatient to usePatient

### PR DESCRIPTION
**Pull request by brandones**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

## Summary

This PR switches from useCurrentPatient to usePatient, per https://github.com/openmrs/openmrs-esm-core/pull/265 . This PR should be updated with the new dependency once that is merged.

### CODE REVIEW

**Comment by denniskigen** [comment]
@brandones, this is failing because:

Screenshot 2022-01-24 at 18 07 18

**Comment by brandones** [comment]
Yeah, all of these PRs need a `yarn upgrade @openmrs/esm-framework`.

**Comment by denniskigen** [comment]
Doing so upgrades it to a `pre-` prefixed version, not `next`. Is cutting a new release of `esm-core` the best approach, @brandones?

**Comment by brandones** [comment]
Yeah it's sort of awkward, the procedure I follow is

```
yarn upgrade @openmrs/esm-framework
# change the `pre` version back to the `next` version
yarn
```

I wish yarn would just... not change the version number when you use the `upgrade` command.

**Review by denniskigen — APPROVED** [review]
LGTM! Thanks so much for the work, @brandones!

**Comment by brandones** [comment]
Thanks for completing it, @denniskigen !

**Pull request merged**
