### PR TITLE
(fix) O3-3781: Custom Widgets throwing error when rendering.

### PR DESCRIPTION
**Pull request by usamaidrsk**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

 Fix can not read from undefined Custom Widget. 
A quick test, use [this config](https://pastebin.ubuntu.com/p/S4HbRnTv7D/), provided by Reagan [on this slack thread](https://openmrs.slack.com/archives/CHP5QAE5R/p1723131505666589)
 
## Screenshots

image

## Other

https://openmrs.atlassian.net/browse/O3-3781

### CODE REVIEW

**Comment by vasharma05** [comment]
@usamaidrsk, the PR titles should be specific to user case, instead of technical issue/ improvement.
For this PR, the correct PR title will be: (fix) O3-3781: Custom Widgets throwing error when rendering.

Then the description will state the technical issue.

**Review by vasharma05 — DISMISSED** [review]
@usamaidrsk , please add a screenshot, @kazlaw can you please provide the configuration for adding a custom widget?
Thanks!

**Comment by kazlaw** [comment]
> > @usamaidrsk , please add a screenshot, @kazlaw can you please provide the configuration for adding a custom widget? Thanks!
> 
> Section definition: https://github.com/mekomsolutions/ozone-hsc/blob/9961272440baeaa49449f9596604114365967711/configs/openmrs/frontend_config/ozone-frontend-config.json#L7
> 
> Field definition: https://github.com/mekomsolutions/ozone-hsc/blob/9961272440baeaa49449f9596604114365967711/configs/openmrs/frontend_config/ozone-frontend-config.json#L171
> 
> Cc: @vasharma05 , @usamaidrsk

The other place this can be put is here: 

[Screencast from 22-08-24 12:16:43.webm](https://github.com/user-attachments/assets/07f0c9a0-00dc-44b7-bc09-aebd5f3bdc3f)

**Comment by kazlaw** [comment]
> @usamaidrsk , please add a screenshot, @kazlaw can you please provide the configuration for adding a custom widget? Thanks!

@vasharma05 , @usamaidrsk something like this

`    "extensionSlots": {
      "patient-chart-summary-dashboard-slot": {
        "add": [
          "obs-by-encounter-widget#consultation"
        ],
        "order": [
          "obs-by-encounter-widget#consultation"
        ],
        "configure": {
          "obs-by-encounter-widget#consultation": {
            "title": "Motif de consultation",
            "showGraphByDefault": true,
            "encounterTypes": [
              "f9fdbe63-12b4-479f-b8fd-dcbfde6aa944"
            ],
            "Display conditions": {
              "privileges": [
                "Add Users"
              ]
            },
            "data": [
              {
                "label": "Motif de consultation",
                "concept": "0a061333-1611-45b3-8096-f7c339b4fdfc",
                "color": "blue"
              },
              {
                "label": "Duration",
                "concept": "d178d5cf-52c3-4722-bb12-5861daa2815c",
                "color": "green"
              },
              {
                "label": "Time Units",
                "concept": "d6593e37-b7a8-482b-856f-6f6a8db25508",
                "color": "green"
              }
            ],
            "table": {
              "pageSize": 6
            }
          }
        }
      }
    },`

**Review by brandones — APPROVED** [review]
Putting the fix in, since it's kind of a no-brainer. Though fleshing out the associated PR documentation as requested is quite welcome. Thanks @usamaidrsk

**Pull request merged**
