### PR TITLE
Revert "(feat) Migrating Medications order form to use RHF and Zod"

### PR DESCRIPTION
**Pull request by brandones**
Reverts openmrs/openmrs-esm-patient-chart#1309

Previous behavior being restored:
meds-old

Behavior after that PR:
meds-new

### CODE REVIEW

**Review by hadijahkyampeire — COMMENTED** [review]
@brandones does this mean, the form of the medications should not be transformed to use RHF?

**Comment by lumuchris256** [comment]
> @brandones does this mean, the form of the medications should not be transformed to use RHF?

means the first transformation needs reworking (which am currently working on) from observations [here](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1309#issuecomment-1694587720)
I suggest the revert be approved

**Comment by lumuchris256** [comment]
@brandones @hadijahkyampeire 
 I have pushed fresh changes to fix the form straight without need to revert  at https://github.com/openmrs/openmrs-esm-patient-chart/pull/1332/
 please review

**Comment by brandones** [comment]
Looks good, appreciate your quick work on that @lumuchris256 .

**Pull request closed without merging**
