### PR TITLE
(fix) O3-2713: Fix positioning of side rail action badges

### PR DESCRIPTION
**Pull request by usamaidrsk**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR fixes the positioning of alert badges shown for icon links in the side rail.

Design doc - https://zeroheight.com/23a080e38/p/948cf1-siderail-and-bottom-nav/b/86907e

#### Before
image

#### Improvement
image

## Other

[O3-2713](https://openmrs.atlassian.net/browse/O3-2713)

### CODE REVIEW

**Review by njiddasalifu — COMMENTED** [review]
nice, catch @usamaidrsk. @denniskigen should review and merge if applicable

**Review by denniskigen — APPROVED** [review]
Thanks, @usamaidrsk!

**Comment by vasharma05** [comment]
As @denniskigen suggested, please test it on Tablet view as well before this PR gets merged.
Thanks!

**Comment by usamaidrsk** [comment]
> As @denniskigen suggested, please test it on Tablet view as well before this PR gets merged. Thanks!

Yes sure thanks, doing so, will update the description with the screenshot.

**Comment by usamaidrsk** [comment]
@denniskigen , @vasharma05 
This is badges appear on the tablet
image

**Comment by denniskigen** [comment]
Thanks for verifying that, @usamaidrsk!

**Pull request merged**
