### PR TITLE
BREAKING: Clean up patient banner config

### PR DESCRIPTION
**Pull request by brandones**
This is marked as a breaking change because it changes the configuration schema. If there are implementations using `useCustomAddressLabel` or `contactAttributeType`, they will need to migrate.

## Migration

Old config:

```json
{
  "@openmrs/esm-patient-banner-app": {
    "contactAttributeType": ["abcd-1234"],
    "useCustomAddressLabel": {
      "enabled": true,
      "customAddressLabel": {
        "countyDistrict": "Fancy County Name"
}}}}
```

New:

```json
{
  "@openmrs/esm-patient-banner-app": {
    "contactAttributeTypes": ["abcd-1234"],
    "Translation overrides": {
      "en": {
        "countyDistrict": "Fancy County Name"
}}}}
```

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

https://github.com/openmrs/openmrs-esm-patient-chart/pull/1175 introduced a config option that should never have been introduced, since it solves a problem already solved by [translation overrides](https://o3-docs.openmrs.org/docs/configure-o3/configure-translations.en-US#translation-overrides-specific-to-an-individual-o3-module). Perhaps we should flesh out that documentation a bit more; I don't think as many people know about this feature as should. https://github.com/openmrs/openmrs-esm-patient-chart/pull/1197 then doubles down on making problems. See [this comment](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1197#discussion_r1436702089) for guidance on creating config options.

Also https://github.com/openmrs/openmrs-esm-patient-chart/pull/636 created a config key with a singular name (`contactAttributeType`), type UUID, an array for a default, and then in the actual usage only an array would work. I imagine AMPATH will need to update this config key, who's working at AMPATH these days? I can't imagine anyone else is using that config key because it doesn't make any sense as written.

CC @makombe @Jexsie @CynthiaKamau @donaldkibet @denniskigen @vasharma05

### CODE REVIEW

**Comment by brandones** [comment]
Wait, I just realized that the corresponding `contactAttributeType` config [in esm-patient-search-app](https://github.com/openmrs/openmrs-esm-patient-management/blob/ac9eb391db724db13a2b632447e07a4de8a1233f/packages/esm-patient-search-app/src/config-schema.ts#L16-L27) has the UUIDs for telephone number and email as the default value. Which means either the default in that app is wrong, or the description here (that it's for the patient's contact person's contact details) is wrong. I sort of suspect this description is what should be adapted. Should we include phone number and email as default values here? @vasharma05 @donaldkibet

**Review by CynthiaKamau — APPROVED** [review]

**Comment by brandones** [comment]
Ping @vasharma05 @donaldkibet

**Review by donaldkibet — APPROVED** [review]

**Comment by brandones** [comment]
@donaldkibet I have a question for you or @vasharma05 :

> the corresponding contactAttributeType config [in esm-patient-search-app](https://github.com/openmrs/openmrs-esm-patient-management/blob/ac9eb391db724db13a2b632447e07a4de8a1233f/packages/esm-patient-search-app/src/config-schema.ts#L16-L27) has the UUIDs for telephone number and email as the default value. Which means either the default in that app is wrong, or the description here (that it's for the patient's contact person's contact details) is wrong. I sort of suspect this description is what should be adapted. Should we include phone number and email as default values here? @vasharma05 @donaldkibet

**Comment by ibacher** [comment]
> Which means either the default in that app is wrong, or the description here (that it's for the patient's contact person's contact details) is wrong. I sort of suspect this description is what should be adapted. Should we include phone number and email as default values here?

Or the third option, which is that we have two poorly named, non-overlapping configuration options. AMPATH does use a patient attribute to indicate the patient's contact person rather than relationships (relationships require the creation of a backend Person object), whereas the search app does make some effort to load the patients email and telephone number. I do suspect we'll need some way of handling implementation-specific attributes without massive code changes.

That said, AFAIK, the roll-out of O3 at AMPATH is somewhat stalled.

> Perhaps we should flesh out that documentation a bit more; I don't think as many people know about this feature as should.

I agree. We should also make some effort to come up with some rules about what belongs in a frontend configuration, e.g., incorporating the guidance you linked to about booleans and what is my personal bugbear: never put display strings in the configuration.

**Review by ibacher — APPROVED** [review]

**Comment by ibacher** [comment]
Looks like this needs some conflicts to be resolved, but otherwise, LGTM

**Pull request merged**
