### PR TITLE
(test) O3-2344: Change table locators

### PR DESCRIPTION
**Pull request by RandilaP**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
- Goal of this PR is to fix the unexpected e2e tests that are occurring due to the locating same test results in tables.

## Related Issue

https://issues.openmrs.org/browse/O3-2344

### CODE REVIEW

**Comment by RandilaP** [comment]
@anjula-sack @jayasanka-sack @Piumal1999 Could you please review this PR

**Comment by anjula-sack** [comment]
@RandilaP can you create an issue for this and link?

**Comment by anjula-sack** [comment]
@RandilaP The tests are still failing

**Review by anjula-sack — APPROVED** [review]
Thank you! @RandilaP

**Pull request merged**
