### PR TITLE
Filter by encounter types implemented in observation endpoint on esm-generic-patient-widgets-app

### PR DESCRIPTION
**Pull request by icrc-agomes**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
In esm-generic-patient-widgets-app it was needed to implement the filter of observations endpoint by encounter type

### CODE REVIEW

**Review by ibacher — CHANGES_REQUESTED** [review]
@icrc-agomes Could you look into the failing tests. Likely we need to update a mock somewhere to ensure `encounterTypes` is always an empty array.

**Review by ibacher — CHANGES_REQUESTED** [review]
Thanks @icrc-agomes! Couple of small things.

**Comment by icrc-agomes** [comment]
@ibacher Hello Ian sorry for the late reply. There were some complications with this branch, all changes were made in this one https://github.com/openmrs/openmrs-esm-patient-chart/pull/854

If you can check it I would appreciate it.

**Comment by gracepotma** [comment]
@icrc-agomes can we close/cancel this PR if https://github.com/openmrs/openmrs-esm-patient-chart/pull/854 is now the desired source of truth?

**Comment by icrc-agomes** [comment]
> #854

**Pull request closed without merging**
