### PR TITLE
(chore): Unable to view Notes and Type entered about Appointment.(03-1763 & 03-1782)

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
- Retrieve the appointment notes and display them in the table.
- Display the appointment type in the table.

## Screenshots
Screenshot 2023-01-19 at 16 53 08

- Showing very long notes and Appointment Type
Screenshot 2023-01-20 at 00 40 54

## Related Issue
- [Display Appointment Notes](https://issues.openmrs.org/browse/O3-1763)
- [Display Appointment Type](https://issues.openmrs.org/browse/O3-1782)

### CODE REVIEW

**Comment by gracepotma** [comment]
Looks good Hadijah! Have you tested what happens if someone writes something like a 2 sentence note, or a large note? E.g. does the text wrap or does it get hidden? (you can always use the ipsem lorem generator for quick text to copy-paste to test this: https://www.lipsum.com/)

**Comment by gracepotma** [comment]
Looks excellent! Thanks so much

**Review by gracepotma — APPROVED** [review]

**Comment by gracepotma** [comment]
@denniskigen could you review this from a code perspective and merge if you're happy w/ it?

**Comment by hadijahkyampeire** [comment]
@denniskigen this is waiting on your approval 🙂

**Review by denniskigen — APPROVED** [review]
Thank you, @hadijahkyampeire!

**Pull request merged**
