### PR TITLE
(chore) Bump @openmrs/ngx-formentry to the latest version

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
Run `yarn up @openmrs/ngx-formentry@next` to update the `form entry` version

### CODE REVIEW

**Comment by ibacher** [comment]
Can't merge this in as this doesn't build. @denniskigen Do you think this is related to the prefix change that got merged the other day? Do we just need to make [this change](https://github.com/openmrs/openmrs-ngx-formentry/pull/13/files#diff-8d554c98f4c32fee762d6a18e8e189f8898124312ba390bdc51fadd38345674fR3) in this repo?

**Comment by denniskigen** [comment]
@ibacher, that's correct. We need to append the `ofe-` prefix to `form-renderer` component selector.

**Comment by hadijahkyampeire** [comment]
@ibacher @denniskigen I have made the above change.

**Review by rbuisson — APPROVED** [review]

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
Thanks, @hadijahkyampeire!

**Pull request merged**
