### PR TITLE
code_refactor on Program form

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
Instead of having a ternary with two branches with the same text in each, I created a little mini-component for the program select and then wrapped it in a layer.

### CODE REVIEW

**Review by vasharma05 — APPROVED** [review]
Thanks @jwnasambu

**Comment by vasharma05** [comment]
Please do have a look at the tests.
Thanks!

**Review by vasharma05 — CHANGES_REQUESTED** [review]
Please make the changes as discussed in the Coffee Break today.
Thanks!

**Review by vasharma05 — APPROVED** [review]
LGTM, thanks @jwnasambu!

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @jwnasambu

**Pull request merged**
