### PR TITLE
(chore) Update translations from Transifex

### PR DESCRIPTION
**Pull request by befantasy**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by befantasy** [comment]
The github auto action for pull translation from transifex still has some problem. So, I update a latest Chinese translation manually.

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
Thanks, @befantasy. Are you still working on this or is it good to go?

**Comment by befantasy** [comment]
It's hard to say. I've spent a lot of time and effort on understanding and solving the data synchronization issue between Transifex and GitHub, rather than the translation work itself... However, so far, it seems that this problem has not been fully resolved. I have translated the vast majority of resources on Transifex, but these translated resources have not been automatically synchronized to GitHub, which is why I submitted this pull request. Additionally, some source strings awaiting translation have not been synchronized from GitHub to Transifex.

**Comment by befantasy** [comment]
> Thanks, @befantasy. Are you still working on this or is it good to go?

Now the source English resources have been mostly synchronized to Transifex, and I have also completed all the Chinese localization work on Transifex. I hope the Chinese language pack can be merged and synchronized into the latest dev and beta versions as soon as possible.

**Pull request merged**
