### PR TITLE
Fix "Basket icon stays selected when entering a form"

### PR DESCRIPTION
**Pull request by nanfuka**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

## Summary
At the moment this ticket is dependent on [this](https://github.com/openmrs/openmrs-esm-patient-chart/pull/814) pr. which is expected to launch the forms upon clicking the form icon. so fo the sake of testing, I tested with the notes. when a user opens the OrderBasket and leaves it open and then clilcks on the notes icon, the notes page becomes the active page and hence the notes icon becomes active. If the user did begin typing / entering an Order but hasn't saved it, the functionality of is also on a different ticket.

## Screenshots
[Screencast from 27-01-23 18:56:16.webm](https://user-images.githubusercontent.com/29108523/215133259-482f7d7b-b91b-4ccc-9743-242e7db26c27.webm)

## Related Issue
[](https://issues.openmrs.org/browse/O3-1775)

### CODE REVIEW

**Comment by hadijahkyampeire** [comment]
@nanfuka do we have a ticket for this work, I am try to understand what this PR was meant to fix, do we still need it?

**Comment by nanfuka** [comment]
@hadijahkyampeire [this is the ticket ](https://issues.openmrs.org/browse/O3-1775).
About wether we still need this pr, @denniskigen had some suggestions about that functionality so at the moment there seems to be another way of going about it. may be we should get some feedback from @denniskigen

**Comment by denniskigen** [comment]
@vasharma05 based on @brandones' and your recent work, is this fix still needed?

**Comment by vasharma05** [comment]
No @denniskigen , we can close this, I've implemented it in the new workspace nav buttons

**Comment by vasharma05** [comment]
Thank you @nanfuka for the work!!!

**Pull request closed without merging**
