### PR TITLE
Hover state: Show full name on hover

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Screenshots

https://user-images.githubusercontent.com/33891016/211933851-cd5a988d-98b5-44e7-a7b6-ec2e240337f6.mp4

## Related Issue
https://issues.openmrs.org/browse/O3-1255

### CODE REVIEW

**Comment by jwnasambu** [comment]
@hadijahkyampeire kindly feel free to review my PR at your convinient time please!

**Review by hadijahkyampeire — APPROVED** [review]
Thanks @jwnasambu. Lgtm

**Comment by vasharma05** [comment]
Re-opening the ticket.
CC: @hadijahkyampeire

**Comment by hadijahkyampeire** [comment]
I would suggest that we let @jwnasambu work on the style fixes as a follow up, no need to keep the fix we have open, the main issue was the hover not working, so the styling fix can come as a follow up. Just for convenience cc @vasharma05

**Pull request merged**
