### PR TITLE
(refactor) O3-3654: Results filter refinement

### PR DESCRIPTION
**Pull request by arodidev**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR introduces a new layout for the results tree filter on the results viewer page, as per [these Zeplin design](https://app.zeplin.io/project/60d59321e8100b0324762e05/screen/66a35f3aa150902a68267832). 
Changes include :
- Removing of refresh button
- Replacing tree and panel views with individual and timeline results
- Replacing configurable link to results view with a modal

## Screenshots

https://github.com/user-attachments/assets/f8ab4a8f-c3f7-47ab-b0e2-0f2b647c129b

## Related Issue

https://openmrs.atlassian.net/browse/O3-3654

### CODE REVIEW

**Review by CynthiaKamau — COMMENTED** [review]
Thanks @arodidev , it looks like this pr is related to [this](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1937/files)

**Comment by arodidev** [comment]
@CynthiaKamau ah I see, this might cause some conflict since mine is also somewhat of a UI overhaul.

**Comment by arodidev** [comment]
Looping in @reagan-meant

**Comment by reagan-meant** [comment]
@arodidev @CynthiaKamau are we doing away with the idea of panels and trees in favour of only an expandable tree?

**Review by CynthiaKamau — APPROVED** [review]

**Review by CynthiaKamau — APPROVED** [review]

**Comment by hadijahkyampeire** [comment]
@CynthiaKamau you have some e2e tests failing, I think this is the issue @denniskigen and @jayasanka-sack mentioned

**Pull request merged**
