### PR TITLE
(fix) 03-1968: Panel and tree views should be full-width when the `full` button is clicked

### PR DESCRIPTION
**Pull request by hadijahkyampeire**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
This PR implements the full view of the test results in the tree and panel mode.

## Video
https://www.loom.com/share/5c316ce5de7a45028953ecf4f6b8abec

## Related Issue
https://issues.openmrs.org/browse/O3-1968

### CODE REVIEW

**Comment by vasharma05** [comment]
Please share the screenshots/ videos too.
Thanks!

**Comment by vasharma05** [comment]
Hi @hadijahkyampeire !

In full view, the switch for Tree/Panel view shouldn't be hidden in full view
image

image

**Comment by vasharma05** [comment]
Else looks all good!

**Comment by hadijahkyampeire** [comment]
> Hi @hadijahkyampeire !
> 
> In full view, the switch for Tree/Panel view shouldn't be hidden in full view image
> 
> image

Thanks @vasharma05 I will fix that.

**Comment by hadijahkyampeire** [comment]
> Please share the screenshots/ videos too. Thanks!

Isn't that loom link working for you? please let me know if it doesn't.

**Comment by vasharma05** [comment]
Ohh, I don't know, missed it out in the first time


Sincere apologies

**Comment by hadijahkyampeire** [comment]
@vasharma05 I have implemented the feedback of showing the panel/tree switcher even in full view.
Screenshot 2023-03-16 at 15 43 33

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks!

**Comment by hadijahkyampeire** [comment]
Thanks @denniskigen for the cleanups.

**Pull request merged**
