### PR TITLE
O3-956: Workspace should auto-scroll to top

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).
- [x] I checked for feature overlap with [**existing widgets**](https://om.rs/directory).

## Summary

The workspace should smoothly scroll to the top of the container when launched, obviating the need for the user to do so manually.

## Video

https://user-images.githubusercontent.com/8509731/144903839-a06474b5-f826-42df-9f99-48a34bdd72d1.mp4

### CODE REVIEW

**Comment by jonathandick** [comment]
Is it possible to have the workspace alone auto-scroll? It seems sub-optimal to take the user away from the location they currently are in within the chart-review. My understanding is that the workspace should be functioning independently of the chart-review area.

**Comment by denniskigen** [comment]
Oh nice, @jonathandick, I hadn't even considered that. I'll work on a solution for that.

**Comment by jonathandick** [comment]
@denniskigen any updates on this?

**Comment by denniskigen** [comment]
Not yet @jonathandick, I'll revisit it now that https://github.com/openmrs/openmrs-esm-patient-chart/pull/480 got merged.

**Comment by denniskigen** [comment]
@jonathandick closing in favour of https://github.com/openmrs/openmrs-esm-patient-chart/pull/492.

**Pull request closed without merging**
