### PR TITLE
(Fix): chart review component optimized

### PR DESCRIPTION
**Pull request by Madhu-mac**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary
 This PR will add functionality in the code by adding usememo for better callback usage & also added error handling on top of it for better optimized performance and readability in the code

### CODE REVIEW

**Comment by Madhu-mac** [comment]
@jwnasambu @denniskigen 
Can you verify this PR once

**Comment by jwnasambu** [comment]
@Madhu-mac Kindly do mind attaching the ticked you are working on please?

**Comment by Madhu-mac** [comment]
@jwnasambu It doesn't have any tickets raised on this. I've added enhancement to the code for optimization and better results

**Comment by brandones** [comment]
Hi @Madhu-mac it's not obvious to me that this would improve performance. Whether `useMemo` improves performance depends on what it's being used for. Could you please provide some evidence that this improves performance?

**Comment by denniskigen** [comment]
I agree with @brandones here. It would help to have at the very least some before and after profiling data from the React Dev tools to support the claim. Also, it'd be ideal to file a ticket first related to addressing performance concerns in the Patient Chart. Feel free to reopen this PR when you have these pre-requisites taken care of. Thanks!

**Pull request closed without merging**
