### PR TITLE
(fix)O3-2416 : Update README file in patient chart

### PR DESCRIPTION
**Pull request by ImethP2**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
Updated the README file in patient chart

## Related Issue
https://issues.openmrs.org/browse/O3-2416

### CODE REVIEW

**Comment by ImethP2** [comment]
@RandilaP can you check this?

**Review by RandilaP — APPROVED** [review]

**Review by RandilaP — APPROVED** [review]
Good job @ImethP2

**Comment by RandilaP** [comment]
@jayasanka-sack this looks good to me. Can you merge it?

**Review by jayasanka-sack — APPROVED** [review]
Thanks @ImethP2 !

**Pull request merged**
