### PR TITLE
O3-1176: Hamburger/Left Nav disappears in Tablet View

### PR DESCRIPTION
**Pull request by 99sumedha**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [ ] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by 99sumedha** [comment]
@denniskigen draft PR for esm-patient-chart

**Comment by gracepotma** [comment]
Thank you for pushing this so quickly @99sumedha!! Sorry about the sudden rush. Nothing personal - we just wanted to unblock the staff in the field :)

**Comment by 99sumedha** [comment]
Hey @gracepotma, I'm sorry about the delay. The issue is still in progress. I will have chat with Dennis about that... :)

**Comment by brandones** [comment]
Closing in favor of https://github.com/openmrs/openmrs-esm-core/pull/375.

**Pull request closed without merging**
