### PR TITLE
(chore) Add Chinese translations

### PR DESCRIPTION
**Pull request by ibacher**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Chinese translations thanks to @befantasy

### CODE REVIEW

**Comment by denniskigen** [comment]
Thanks, @ibacher. Do you intend to translate all the content in the Chinese translation files or is that something you'll defer to Transifex?

**Comment by ibacher** [comment]
@denniskigen Well, these were translated by someone who speaks Chinese. I do not really trust Google Translate or the like to give us the kind of quality we should aim to have, so I'll defer to Transifex updates.

**Comment by denniskigen** [comment]
Cool, thanks!

**Review by denniskigen — APPROVED** [review]
LGTM. Thanks, @ibacher, @befantasy!

**Pull request merged**
