### PR TITLE
(fix) Eliminate the need for dashboards to have names

### PR DESCRIPTION
**Pull request by brandones**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary

This removes the "name" attribute of dashboards. The title is used for everything.

## Screenshots

Peek 2022-04-14 17-24

### CODE REVIEW

**Comment by brandones** [comment]
Doing something more radical.

**Comment by brandones** [comment]
Just kidding, just renamed "title" to "name," nothing radical for now.

**Review by ZacButko — APPROVED** [review]

**Comment by ibacher** [comment]
@brandones I'm curious about a point on this: how will this change interact with i18n? For instance, if I replace "Allergy" with "Alergia" does this also change the URL? (Can this be done?)

**Comment by brandones** [comment]
Also not sure what happened to this change:

> Just kidding, just renamed "title" to "name," nothing radical for now.

Maybe I forgot to push...

**Comment by ibacher** [comment]
> We could, but it would be pretty ugly and increase the chance of weird errors loading dashboards. I would prefer just to do i18n where we are displaying the title.

Oh, I absolutely agree that we should only do i18n where we are displaying the title and leave the URLs stable across versions. My concern is mostly just how we enable overriding the title in the left nav and breadcrumb without also overriding the title in the url.

**Comment by brandones** [comment]
Oh yeah. Well right now we actually don't support overriding dashboard titles. I mean, the patient chart in the abstract [supports it](https://github.com/openmrs/openmrs-esm-patient-chart/blob/master/packages/esm-patient-chart-app/src/patient-chart/chart-review/chart-review.component.tsx#L41), but actually existing dashboards don't have configuration schemas associated with them, so they are effectively not configurable.

It seems like we should probably not make the titles overridable via config, but rather using i18n (and therefore i18n overrides in config).

**Pull request merged**
