### PR TITLE
(feat) Migrating Medications order form to use RHF and Zod

### PR DESCRIPTION
**Pull request by lumuchris256**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
Migrated the form to use reachthookform and zod 

## Screenshots
[Screencast from 2023-08-14 13-25-47.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/59338693/52c10e07-21bc-4644-9603-8f15bed5990d)

## Related Issue
https://issues.openmrs.org/browse/O3-2141

## Other
cc @denniskigen @hadijahkyampeire

### CODE REVIEW

**Review by hadijahkyampeire — APPROVED** [review]
LGTM, thanks @lumuchris256

**Comment by brandones** [comment]
This neither looks acceptable nor works correctly.

[Screencast from 2023-08-26 15-22-53.webm](https://github.com/openmrs/openmrs-esm-patient-chart/assets/1031876/0c040454-9ffd-463d-aa75-bc7fa27523b3)

**Comment by lumuchris256** [comment]
thanks for the re-review @brandones looking into it

**Comment by brandones** [comment]
There's also the fact that required-but-unfilled fields no longer get little notifications that say "Please fill out this field."

**Pull request merged**
