### PR TITLE
(fix) O3-2604: Add a “refresh data“ button to the test results viewer

### PR DESCRIPTION
**Pull request by jwnasambu**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
I created a "Refresh Data" button on the far right section header. When clicked, the window.location.reload() method reloads the current page, effectively refreshing the content with new changes.

## Screenshots

https://github.com/openmrs/openmrs-esm-patient-chart/assets/33891016/30e6ef9a-a896-4b62-870e-b96de76f507f

## Related Issue
https://openmrs.atlassian.net/browse/O3-2604

### CODE REVIEW

**Comment by jwnasambu** [comment]
@ibacher Kindly did you anticipate something like this?

**Comment by denniskigen** [comment]
Latest commit just cleans up the UI a touch:

CleanShot 2024-03-26 at 1  32 50@2x

**Review by denniskigen — APPROVED** [review]
Thanks, @jwnasambu. Happy with the approach, @ibacher?

**Comment by ibacher** [comment]
LGTM. Thanks @jwnasambu!

**Pull request merged**
