### PR TITLE
(feat) O3-1422 / O3-2724: Move workspace system into the framework

### PR DESCRIPTION
**Pull request by brandones**
DEPENDS ON: https://github.com/openmrs/openmrs-esm-core/pull/979

## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary

Apologies for the big PR. It is generally quite trivial. I have gone through and tested every single app that has a workspace.

## Screenshots
See the main core change.

## Related Issue
https://openmrs.atlassian.net/browse/O3-1421
https://openmrs.atlassian.net/browse/O3-2724

## Other

Depends on https://github.com/openmrs/openmrs-esm-core/pull/979

### CODE REVIEW

**Comment by brandones** [comment]
Yikes. I have not worked on `esm-form-entry-app` and am struggling to figure out how to address the build errors. Looks like it doesn't have an independent `typescript` step; when I run `tsc` on it it gives some totally different errors. I messed with the `tsconfig.json` in all the ways I could think to and none of it changed the error at all. I'll keep messing with it, but @ibacher @denniskigen if you have any suggestions they would be very welcome.

```
@openmrs/esm-form-entry-app:build
  cache miss, executing 4e5fb2c3b0084a01
  - Generating browser application bundles (phase: setup)...
  ✔ Browser application bundle generation complete.
  ✔ Browser application bundle generation complete.
  
  Warning: /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/packages/esm-form-entry-app/src/app/openmrs-api/program-resource.service.ts depends on 'dayjs'. CommonJS or AMD dependencies can cause optimization bailouts.
  For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
  
  Warning: /home/runner/work/openmrs-esm-patient-chart/openmrs-esm-patient-chart/packages/esm-form-entry-app/src/app/openmrs-api/program-resource.service.ts depends on 'dayjs/plugin/utc'. CommonJS or AMD dependencies can cause optimization bailouts.
  For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
  
  
  
  Error: Error: ../../node_modules/@openmrs/esm-styleguide/src/custom-overflow-menu/custom-overflow-menu.component.tsx:5:20 - error TS2307: Cannot find module './custom-overflow-menu.module.scss' or its corresponding type declarations.
  
  5 import styles from './custom-overflow-menu.module.scss';
                       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  
  
  Error: Error: ../../node_modules/@openmrs/esm-styleguide/src/datepicker/openmrs/openmrs-date-picker.component.tsx:79:7 - error TS2322: Type 'Function' is not assignable to type 'Hook'.
    Type 'Function' provides no match for the signature '(dates: Date[], currentDateString: string, self: Instance, data?: any): void'.
  
  79       onClose={carbonOptions?.onClose}
           ~~~~~~~
...
```

**Comment by ibacher** [comment]
The first of those errors is why every `declarations.d.ts` file has this line:

```ts
declare module '*.scss';
```

That makes the TS compiler happy.

The second one is probably one we've been ignoring because we usually have `declare module '@carbon/react'` because Carbon's types are still at mess (at least at the version we're on). Technically, Typescript is not wrong, just annoyingly strict there.

**Comment by brandones** [comment]
Sorry, yeah, forgot to mention that actually the first thing I tried was adding those declarations back to `esm-form-entry-app/src/declarations.d.ts`. Doesn't seem to change anything, surprisingly.

I've had so little luck getting anything to have any effect at all that I tried deleting the contents of `tsconfig.json` and re-building as a sanity check :laughing: That, fortunately, brought up different errors. So at least my head is attached correctly to my neck.

Deleting the whole contents of `esm-form-entry-app/src/declarations.d.ts`, however, does not appear to change the error at all—even to produce new errors due to the missing declaration of the `Window` interface. I remain befuddled.

**Comment by ibacher** [comment]
Alright, so we had that commit that moved the ambient declarations from the styleguide into the framework. By adding that _explicitly_ to the includes, it appears to fix the TS issues. Possibly the ambient types are exported from `internal.ts` in the framework? The TS configuration for form-entry-app explicitly resolves `@openmrs/esm-framework` to `@openmrs/esm-framework/src/internal` since, unlike our other applications, Angular actually uses `tsc` to produce the output scripts.

**Comment by brandones** [comment]
Amazing, thank you @ibacher . Good thinking, that makes sense. This PR is now actually fully ready for review.

**Review by ibacher — APPROVED** [review]
LGTM. Thanks @brandones!

**Review by denniskigen — APPROVED** [review]
LGTM, @brandones. Excellent work. Are we deprecating `registerWorkspace`?

**Comment by denniskigen** [comment]
Good to go, @ibacher?

**Comment by ibacher** [comment]
> Are we deprecating registerWorkspace?

Yes. The workspace registration via routes.json is basically an improvement in almost every way.

> And can we update the [naming conventions](https://o3-docs.openmrs.org/docs/coding-conventions#naming) in the docs to include the new workspace and modal suffixes?

Yes.

**Pull request merged**
