### PR TITLE
added readme

### PR DESCRIPTION
**Pull request by tencups**

### CODE REVIEW

**Comment by jonathandick** [comment]
This looks to be the existing documentation for esm-api. Did you mean to copy to the readme for patient chart?

**Comment by tencups** [comment]
Yeah, I basically just transformed it into markdown.

**Comment by jonathandick** [comment]
Could you add this to esm-api module: https://github.com/openmrs/openmrs-esm-api

**Comment by tencups** [comment]
Yes, I'll try to do that. Thanks :)

**Pull request closed without merging**
