### PR TITLE
BREAKING: Merge vitals and biometrics apps

### PR DESCRIPTION
**Pull request by ibacher**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary

Essentially, this merges the biometrics app into the vitals app. The main motivation is to clean-up the shared configurations and SWR caching.

### CODE REVIEW

**Comment by gracepotma** [comment]
Hi @ibacher, question about this work: What would be the implications of this for sites that don't actually want the biometrics app to show up everywhere the Vitals app does? E.g. IIRC at some sites, like Ampath, they wanted the VS chart on the pt summary, but not the Biometrics table. Do implementers lose that configurability?

**Comment by ibacher** [comment]
> Do implementers lose that configurability?

No. They have the same configurability options. The biometrics table can easily be removed using the config system, which remains our preferred mechanism for implementations to opt out of functionality. (As long as the biometrics table is configured to not show, there's no substantive performance impact to having the bundle avaiable).

**Comment by ibacher** [comment]
@denniskigen I'd appreciate a review here when you get the chance. I'd like to get this in before replacing the `getAsyncLifecycle()` stuff mostly because this PR is getting unwieldy.

**Review by denniskigen — APPROVED** [review]
Excellent work, @ibacher. LGTM!

**Pull request merged**
