### PR TITLE
(fix) Fix medications display in visit summary

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR fixes the medications UI in the visit summary dashboard to align them closer with the [designs](https://zeroheight.com/23a080e38/p/41d6df-data-tile).

## Screenshots

> Before

CleanShot 2024-01-17 at 5  08 19@2x

> After

CleanShot 2024-01-17 at 10  43 55@2x

### CODE REVIEW

**Comment by denniskigen** [comment]
Just occurred to me that the dose units need to be pluralized.

**Comment by ibacher** [comment]
The quantities there are also weird. 4 tablets twice a day for 2 weeks should be 112 tablets. Similarly 3 tablets twice a day for 10 days requires 60 tablets, not 2.

**Comment by denniskigen** [comment]
Yeah, seems like the order basket shouldn't have let the provider get away with these values:

CleanShot 2024-01-17 at 11  03 28@2x

**Review by ibacher — APPROVED** [review]
Definitely an improvement!

**Comment by denniskigen** [comment]
I'll ticket out the bits that need looking into on Jira. Thanks for the review, @ibacher!

**Pull request merged**
