### PR TITLE
(chore) Remove forms and notes

### PR DESCRIPTION
**Pull request by ibacher**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

Removes the Forms & Notes dashboards as we have better versions of both (form workspace and visit summary) and no longer need these components.

### CODE REVIEW

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
@donaldkibet @CynthiaKamau do you agree with removing this widget in lieu of the existing workspace-level support for forms and the visit summary widget?

**Comment by ojwanganto** [comment]
@denniskigen sorry to ask, could you briefly describe how the new approach will work? A picture showing the same can also help with understanding the concept. Thanks

**Comment by donaldkibet** [comment]
@ibacher @denniskigen I'm generally on board with the changes, but I have one concern about our implementation. Currently, we have two tabs: one displaying available forms and the other showing completed forms. The completed forms tab also offers a shortcut to edit the filled form associated with the active visit. Removing this shortcut means users will have to navigate to the visits and encounter page to locate the encounter and edit it from there. While this is still acceptable, we've received feedback about the inconvenience of multiple clicks required to perform a simple task. It would be great if we could also address this concern on the form-dashboard. Thanks! cc @ojwanganto @CynthiaKamau

**Comment by ibacher** [comment]
> The completed forms tab also offers a shortcut to edit the filled form associated with the active visit. 

Part of the motivation here is actually that the edit widget in the completed forms doesn't work properly anyway (i.e., it appears for all forms, even forms that haven't been submitted, which causes it to hang endlessly; it isn't restrict to the current visit—it's literally just editing whatever encounter the form was last entered for, etc.). I don't think there's any reason that we shouldn't be able to provide an edit form link in the workspace, though.

**Comment by ojwanganto** [comment]
This is helpful, Ian. Are there some designs for the current
implementation? We hope a smooth transition for those currently using o3 in
the pilot facilities.

**Comment by vasharma05** [comment]
Hi @ojwanganto @donaldkibet !
Moving ahead to merge this in the next hour. Please raise any concerns, in case.
Thanks!

**Pull request merged**
