### PR TITLE
O3-2535 Enhance actions menu items display in small tabs

### PR DESCRIPTION
**Pull request by CynthiaKamau**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

-  Enhance actions menu items display in small tabs
- 
## Screenshots

**Before :**
before

**After**
After

### CODE REVIEW

**Comment by denniskigen** [comment]
This change will break the actions menu UI for folks using the Patient Lists frontend module. Could you find an approach that works for cases where folks use Patient Lists and otherwise?

**Comment by CynthiaKamau** [comment]
> This change will break the actions menu UI for folks using the Patient Lists frontend module. Could you find an approach that works for cases where folks use Patient Lists and otherwise?

How so?

**Comment by denniskigen** [comment]
CleanShot 2023-10-31 at 1  39 14@2x

This is what you get with the patient list app enabled in the import map.

**Comment by CynthiaKamau** [comment]
> CleanShot 2023-10-31 at 1  39 14@2x
> 
> This is what you get with the patient list app enabled in the import map.

made an update

**Comment by denniskigen** [comment]
Hey, @CynthiaKamau, does https://github.com/openmrs/openmrs-esm-patient-chart/pull/1471 mean we can close this one?

**Pull request closed without merging**
