### PR TITLE
Add use-value feature to Ampath forms

### PR DESCRIPTION
**Pull request by donaldkibet**
## Requirements

- [x] My work conforms to the [**OpenMRS 3.0 Styleguide**](https://om.rs/styleguide).

## Summary

- This PR adds the ability to use the `use-value` feature of Ampath form engine
- Added loading spinner while loading the form

## Screenshots

use-value

## Issue

*None.*

## Other

*None.*

### CODE REVIEW

**Comment by jonathandick** [comment]
@enyachoke are you able to provide review of this?

**Review by enyachoke — CHANGES_REQUESTED** [review]
@donaldkibet  please check the comments I made

**Comment by jonathandick** [comment]
@donaldkibet what is the status of this PR?

**Comment by donaldkibet** [comment]
> @donaldkibet what is the status of this PR?

working on this should close this one in the next two days

**Comment by jonathandick** [comment]
@enyachoke would you mind reviewing the requested changes made by donald so we can get this merged?

**Comment by enyachoke** [comment]
@donaldkibet  we still need to look into the identifier issue. We can have a catch up on it if necessary.

**Comment by jonathandick** [comment]
@donaldkibet any updates on this?

**Review by enyachoke — APPROVED** [review]

**Comment by donaldkibet** [comment]
Thanks @enyachoke  for the review

**Pull request merged**
