### PR TITLE
(fix) enable 'see all results' to show all results in visits

### PR DESCRIPTION
**Pull request by arodidev**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR fixes the issue where the "See all results" and "More reults available" button in the Tests tab within visit summaries was redirecting the user to the Patient summary instead of displaying all available results.
## Screenshots

https://github.com/openmrs/openmrs-esm-patient-chart/assets/51090527/4d3b836d-93d8-448a-80be-46d0996924b6

### CODE REVIEW

**Comment by CynthiaKamau** [comment]
Thanks @arodidev , kindly add a screenshot or short video for the functionality

**Comment by vasharma05** [comment]
I believe the button should be at the end with a Chevron down icon in it.
The arrow `->` shows redirection, which we are not doing here.
Thanks!

**Comment by arodidev** [comment]
> I believe the button should be at the end with a Chevron down icon in it. The arrow `->` shows redirection, which we are not doing here. Thanks!

@vasharma05 this will be rectified, thank you.

**Comment by ibacher** [comment]
The intention of the "See All Results" link was to move the user into the test results view, not displaying them as part of the visit view. Fixing this behaviour is probably just a matter of fixing the URL.

**Review by ibacher — CHANGES_REQUESTED** [review]
See my previous comment

**Comment by arodidev** [comment]
> The intention of the "See All Results" link was to move the user into the test results view, not displaying them as part of the visit view. Fixing this behaviour is probably just a matter of fixing the URL.

Ah... I see. Thank you for the implementation approach.

**Pull request closed without merging**
