### PR TITLE
Walk-around:Parcel component not working

### PR DESCRIPTION
**Pull request by nkimaina**

### CODE REVIEW

**Comment by fatmali** [comment]
whats the error with the parcel component?

**Comment by nkimaina** [comment]
From the error log, the error is:

zone-evergreen.min.js:1 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Check the render method of `Workspace`.
    at createFiberFromTypeAndProps (react-dom.development.js:26775)
    at createFiberFromElement (react-dom.development.js:26798)
    at reconcileSingleElement (react-dom.development.js:15672)
    at reconcileChildFibers (react-dom.development.js:15732)
    at reconcileChildren (react-dom.development.js:18235)
    at updateHostComponent (react-dom.development.js:18757)
    at beginWork$1 (react-dom.development.js:20339)
    at HTMLUnknownElement.callCallback (react-dom.development.js:330)
    at a.invokeTask (zone-evergreen.min.js:1)
    at s.runTask (zone-evergreen.min.js:1)
createFiberFromTypeAndProps @ react-dom.development.js:26775
createFiberFromElement @ react-dom.development.js:26798
reconcileSingleElement @ react-dom.development.js:15672
reconcileChildFibers @ react-dom.development.js:15732
reconcileChildren @ react-dom.development.js:18235
updateHostComponent @ react-dom.development.js:18757
beginWork$1 @ react-dom.development.js:20339
callCallback @ react-dom.development.js:330
invokeTask @ zone-evergreen.min.js:1
runTask @ zone-evergreen.min.js:1
invokeTask @ zone-evergreen.min.js:1
p @ zone-evergreen.min.js:1
h @ zone-evergreen.min.js:1
invokeGuardedCallbackDev @ react-dom.development.js:379
invokeGuardedCallback @ react-dom.development.js:434
beginWork$$1 @ react-dom.development.js:25926
performUnitOfWork @ react-dom.development.js:24841
workLoopSync @ react-dom.development.js:24817
performSyncWorkOnRoot @ react-dom.development.js:24416
(anonymous) @ react-dom.development.js:12345
unstable_runWithPriority @ react.development.js:2975
runWithPriority$2 @ react-dom.development.js:12295
flushSyncCallbackQueueImpl @ react-dom.development.js:12340
flushSyncCallbackQueue @ react-dom.development.js:12328
discreteUpdates$1 @ react-dom.development.js:24569
discreteUpdates @ react-dom.development.js:1435
dispatchDiscreteEvent @ react-dom.development.js:6015
invokeTask @ zone-evergreen.min.js:1
runTask @ zone-evergreen.min.js:1
invokeTask @ zone-evergreen.min.js:1
p @ zone-evergreen.min.js:1
h @ zone-evergreen.min.js:1
Show 2 more frames
backend.js:6 The above error occurred in the <div> component:
    in div (created by Panel)
    in Panel (created by Workspace)
    in div (created by Tabs)
    in div (created by Tabs)
    in Tabs (created by Workspace)
    in Workspace (created by WorkspaceWrapper)
    in div (created by WorkspaceWrapper)
    in WorkspaceWrapper (created by Context.Consumer)
    in Route (created by Root)
    in main (created by Root)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Root)
    in Root (created by OpenmrsReactRoot(patient-chart))
    in Unknown (created by OpenmrsReactRoot(patient-chart))
    in I18nextLoadNamespace (created by OpenmrsReactRoot(patient-chart))
    in Suspense (created by OpenmrsReactRoot(patient-chart))
    in OpenmrsReactRoot(patient-chart)

**Comment by fatmali** [comment]
I think Parcel is imported from `single-spa-react/Parcel` and not `single-spa-react`

**Comment by nkimaina** [comment]
Tried it. It didn't work. Will have to log a bug in the single-spa-react repo.

**Comment by jonathandick** [comment]
@nkimaina  any updates on reporting the bug to single-spa maintainers?

**Comment by nkimaina** [comment]
@jonathandick I will need to set-up an environment for the purposes of reproducing so that I can report.

**Comment by jonathandick** [comment]
@nkimaina is this ready to merge? Once conflicts are fixed we can do so.

**Comment by jonathandick** [comment]
Let's fix conflicts and then we can merge

**Comment by nkimaina** [comment]
@fatmali will try to see why it's working on her machine and not the online version, then she ca advise.

**Comment by nkimaina** [comment]
@fatmali @jonathandick issue now fixed. Need to still file an issue with single-spa-react to export the right Parcel component, to avoid someone getting stuck in future.

**Comment by jonathandick** [comment]
@nkimaina, can we close this PR or we still need it?

**Comment by fatmali** [comment]
The issue has been resolved. So it can be merged. The issue arised from this:
```
{ ...
component: <Parcel ... />
}
```
when defining a component inside an object, it must be a function, so @nkimaina changed it to this
```
component: () => <Parcel .../>
```
This applies to all jsx elements

**Pull request merged**
