### PR TITLE
Extract a "conditions widget" out of the conditions-forms

### PR DESCRIPTION
**Pull request by samuelmale**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR doesn't introduce any logical semantic changes to Conditions. It just decouples the condition widget from the encompassing static condition form so that we are able to embed this widget within other existing forms. For more details, checkout this [talk thread](https://talk.openmrs.org/t/o3-embedding-conditions-widget-in-forms/36642/3)

## Screenshots

https://www.loom.com/share/df18fb08c2e6432c8e764d8287723566

## Related Issue

https://issues.openmrs.org/browse/O3-1298

## Other
Talk thread --> https://talk.openmrs.org/t/o3-embedding-conditions-widget-in-forms/36642/3

### CODE REVIEW

**Comment by samuelmale** [comment]
@ZacButko could you have any idea of why the CI build is failing yet it passes locally?

**Comment by ZacButko** [comment]
> @ZacButko do you have any idea of why the CI build is failing yet it passes locally?

@samuelmale exit code 137 is an Out Of Memory error. The Github Runners have a large but limited size. @denniskigen attempted to fix this by adding concurrency argument to turborepo in the PR https://github.com/openmrs/openmrs-esm-patient-chart/pull/719. Looks like that PR didn't fully solve the issue

**Review by pirupius — APPROVED** [review]

**Comment by gracepotma** [comment]
Happy to see this merged :D

**Comment by gracepotma** [comment]
What is next?

**Pull request merged**
