### PR TITLE
(fix) Restore some deleted Spanish translations

### PR DESCRIPTION
**Pull request by brandones**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
I accidentally removed some Spanish translations that had been added in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1366 . This restores them.

### CODE REVIEW

**Comment by icrc-jofrancisco** [comment]
Hi @brandones ,
I think there were one or two other files affected (patient-chart-app, flags-app , etc...
Could you fix those as well?
Thanks

**Review by denniskigen — APPROVED** [review]
LGTM

**Comment by brandones** [comment]
Hi @icrc-jofrancisco I'm not seeing the other ones you're talking about. I restored the translations from patient-chart-app and medications-app. Could you point me to where you see those translations getting removed?

**Comment by denniskigen** [comment]
I added those back in in my commit above @brandones

**Comment by icrc-jofrancisco** [comment]
This-> > I added those back in in my commit above @brandones



> I added those back in in my commit above @brandones

Thanks @denniskigen and @brandones !!

**Pull request merged**
