### PR TITLE
(feat)O3-4175 add ability to view and edit completed lab results

### PR DESCRIPTION
**Pull request by Omoshlawi**
## Requirements

- [ ] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

- Added ability to view lab results for completed orders
- Added ability to edit the lab results for completed orders
- The UI is based on [this](https://github.com/openmrs/openmrs-esm-laboratory-app/pull/99) PR

## Screenshots

https://github.com/user-attachments/assets/4ca91a69-bafc-4ed6-a0e2-058a07033792

## Related Issue

https://openmrs.atlassian.net/browse/O3-4175

### CODE REVIEW

**Comment by ojwanganto** [comment]
@Omoshlawi - could we have the edit functionality separate from the new UI enhancments?

**Comment by Omoshlawi** [comment]
> Hi @Omoshlawi you have referenced a PR that is still pending UI feedback. Does this mean the other PR needs to be merged in first before this can get in?

Yes, though the [PR](https://github.com/openmrs/openmrs-esm-laboratory-app/pull/99) now has been merged

Bellow is a short video with most recent changes


https://github.com/user-attachments/assets/f429db1b-44be-4af1-bd42-515d93d77def

**Comment by Omoshlawi** [comment]
> @Omoshlawi - could we have the edit functionality separate from the new UI enhancments?

this PR was only dependent on the extension slot and edit action button introduces in [this pr](https://github.com/openmrs/openmrs-esm-laboratory-app/pull/99).Now that its merged in, it will just plug in the lab result component into extension slot and launch form on edit action button clicked.

**Comment by Omoshlawi** [comment]
Kindly help re review cc @donaldkibet  @denniskigen  @pirupius @ibacher @makombe @ojwanganto

**Comment by pirupius** [comment]
Hi @Omoshlawi thanks for the work on this. Minor UI feedback regarding the way you're displaying the results in the accordion. Please make adjustments to make it similar to the way the orders view is as per the screenshot in a tabular format. This design aligns the content and also shows a range which can be informative to the person viewing 

Screenshot 2024-12-12 at 11 40 52

**Comment by ojwanganto** [comment]
> Hi @Omoshlawi thanks for the work on this. Minor UI feedback regarding the way you're displaying the results in the accordion. Please make adjustments to make it similar to the way the orders view is as per the screenshot in a tabular format. This design aligns the content and also shows a range which can be informative to the person viewing
> 
>Do we really need to show the ranges at this point?

**Comment by ibacher** [comment]
> Do we really need to show the ranges at this point?

For the purposes of UX consistency across the app, I think it makes sense.

**Comment by makombe** [comment]
@pirupius @ibacher @ojwanganto  I have updated the UI to be consistent as requested. Please have a look and review thanks

[Screencast from 13-12-2024 11:19:21 ASUBUHI.webm](https://github.com/user-attachments/assets/4d9af48b-7773-4519-9dd7-207d0a8c5b3a)

**Comment by ojwanganto** [comment]
@pirupius - we should be good now. Please re-review

**Review by pirupius — APPROVED** [review]

**Pull request merged**
