### PR TITLE
(chore) Bump Angular form engine

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR bumps the Angular form engine to the latest available pre-release version.

### CODE REVIEW

**Comment by vasharma05** [comment]
Build failed

**Comment by denniskigen** [comment]
Yeah, I'm pushing the updated lockfile in a sec.

**Comment by denniskigen** [comment]
Hmm, it looks like the Lab test orders form isn't loading in the test environment, hence the failing E2E tests.

CleanShot 2024-04-19 at 1  57 51@2x

**Review by donaldkibet — APPROVED** [review]

**Comment by denniskigen** [comment]
Any reason why the latest [nightly](https://hub.docker.com/layers/openmrs/openmrs-reference-application-3-frontend/nightly/images/sha256-10f7eb870e00485056255fdbe14816b50a85cea99c05129de4740fd5a14346cf?context=explore) might not contain that form, @ibacher?

**Comment by ibacher** [comment]
We removed it [here](https://github.com/openmrs/openmrs-distro-referenceapplication/commit/2a71eb10ea6651a93735ccf94c3dc4d8dfe9cdea), since it's redundant now that there's a lab order basket. Didn't realise there was an e2e test for this.

**Comment by denniskigen** [comment]
That's fine. I can mod the tests to not use to it. Thanks for the heads up, Ian!

**Pull request merged**
