### PR TITLE
(feat) Migrating start visit form to use RHF and Zod

### PR DESCRIPTION
**Pull request by lumuchris256**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary
Migrated the form to use RHF and Zod

## Screenshots
https://www.loom.com/share/eb8972ae8d1a4879942b7aa954913d82?sid=acfe6f65-34eb-4a48-92b3-5faeaaa580be

## Related Issue
https://issues.openmrs.org/browse/O3-2144

## Other
cc @hadijahkyampeire @denniskigen

### CODE REVIEW

**Review by hadijahkyampeire — COMMENTED** [review]
@lumuchris256 the issue I have with this PR is the removal of tests just like on your previous PR, I wonder why the migration would make tests fail, it basically shouldn't. We are going to find ourselves with no tests yet we need to test that the new implementation works well.
So could we have @ayush-AI put back the tests and fix them.

**Review by hadijahkyampeire — APPROVED** [review]
Let's merge this and follow up with the tests

**Comment by jayasanka-sack** [comment]
Hey @lumuchris256, hope you're doing well. It has come to my attention that some failing tests were deleted with the intention of addressing them in a later PR. Unfortunately, this approach has led to the introduction of a bug, as highlighted in this issue: https://github.com/openmrs/openmrs-esm-patient-chart/pull/1346.

To ensure the stability and reliability of our codebase, it's recommended to fix failing tests or include new tests within the same PR. This helps us avoid situations like earlier where our tests become out-of-sync with the development.

I understand that @ayush-AI was assigned to address the deleted tests but he is facing challenges due to their familiarity with the RHF or Zod. Would you kindly consider resolving these tests as soon as possible? Additionally, it would be greatly appreciated if you could also provide a list of any tests that may not have been covered in this migration.

Thank you for your attention to this matter, and your efforts in maintaining the quality of our codebase are highly valued.

cc: @hadijahkyampeire @denniskigen @ibacher @vasharma05

**Comment by lumuchris256** [comment]
> Hey @lumuchris256, hope you're doing well. It has come to my attention that some failing tests were deleted with the intention of addressing them in a later PR. Unfortunately, this approach has led to the introduction of a bug, as highlighted in this issue: #1346.
> 
> To ensure the stability and reliability of our codebase, it's strictly recommended to fix failing tests or include new tests within the same PR. This helps us avoid situations like earlier where our tests become out-of-sync with the development.
> 
> I understand that @ayush-AI was assigned to address the deleted tests but he is facing challenges due to their familiarity with the RHF or Zod. Would you kindly consider resolving these tests as soon as possible? Additionally, it would be greatly appreciated if you could also provide a list of any tests that may not have been covered in this migration.
> 
> Thank you for your attention to this matter, and your efforts in maintaining the quality of our codebase are highly valued.
> 
> cc: @hadijahkyampeire @denniskigen @ibacher @vasharma05

@jayasanka-sack thank you  for the pointers 
the bug was addressed (had a two attributes that had been  missed )
through a coffe break meet  a team me ,ayush and Hadijah (mentor), Denis(mentor) put the follow up  PRs for tests as priority and  we are working on resolving them .( A learning point for me into the tests world )thats the slight delay
But resolved soonest
feel free to track at [this ](https://issues.openmrs.org/browse/O3-2401) and [this ](https://issues.openmrs.org/browse/O3-2402)

**Comment by gracepotma** [comment]
So based on those tickets @lumuchris256 - are you working to fix and re-add the test coverage that you deleted in this PR? 
I strongly support Jayasanka's points above. In this case, to be honest, I do not think it was fair to assign the test fixing to @ayush-AI. It is true that some teams in software development have a "QA department" that writes tests - but more modern practices recommend against having a completely siloed approach to QA like that, because it often results in miscommunication, team blaming, etc. So, we are actively trying to make QA test automation a part of developer expectations in the OpenMRS frontend, as you can see from Ian's [slack note here](https://openmrs.slack.com/archives/CHP5QAE5R/p1694609826707479?thread_ts=1694609233.617749&cid=CHP5QAE5R): "test cases are developer's responsibility, both to add new test cases to cover new features added and to update test cases as your changes cause them to fail. Test cases exist to help us catch regressions in code. If your code breaks a test case, it likely breaks real functionality and the test case needs to be examined." I'm sorry if this comes as a surprise - I know it seems like we have a "dedicated separate QA team" but the intent was to combine that into our usual software processes, not separate them. Thanks for your patience as we try to make this distinction more clear for our community. Any thoughts, concerns, or questions about this approach? :)
If you're unclear on how to write tests for O3, we have new docs here:https://o3-docs.openmrs.org/docs/frontend-modules/testing We'd actually _love_ feedback if there's anything unclear in those docs. And don't be shy to ask questions either on the weekly QA Support Calls or in [#qa-support-team](https://openmrs.slack.com/archives/CP343JH1R)
@hadijahkyampeire a friendly reminder that the same is true for reviewers: "anyone who has commit access to our repos is expected to act as a caretaker for the code they merge, to ensure that it complies with OpenMRS coding standards, including having appropriate tests." ;) 
I do apologize if there were other discussions with @denniskigen that happened that had important context I missed here, e.g. if there was an explicit team decision to break from protocol in this instance. We're still smoothing through the bumps in embedding QA automation into "how we do things" in OpenMRS development :)

**Pull request merged**
