### PR TITLE
O3-1156 Vitals and biometrics boxes does not correctly handle 3 digit…

### PR DESCRIPTION
**Pull request by 99sumedha**
…s values

## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

## Summary

Modified the input text area to support 3 digit values. Issue [O3-1156](https://issues.openmrs.org/browse/O3-1156)

## Screenshots

image

## Related Issue

https://issues.openmrs.org/browse/O3-1156

### CODE REVIEW

**Comment by 99sumedha** [comment]
@vasharma05 PR is open and ready to review.

**Comment by vasharma05** [comment]
Hi @99sumedha!
Since you have made UI changes, please share the screenshots in the summary and do fill the summary details properly.
Thanks!

**Comment by 99sumedha** [comment]
@vasharma05 I cannot get screenshots at the moment due to an error in the patient chart.

**Comment by vasharma05** [comment]
Hi @99sumedha!
You shouldn't push the changes without testing it by yourself.
Please wait for it to be fixed and in the meantime, you can have a look at the other issues.

**Comment by 99sumedha** [comment]
Hi @vasharma05, sorry about that. I did check the changes. Also, we confirmed the changes in the meet we had. I will attach the screenshots when the system is working again.

**Comment by vasharma05** [comment]
Hi @99sumedha!
Any progress in here?

**Comment by 99sumedha** [comment]
@vasharma05 description updated

**Comment by vasharma05** [comment]
Hi @99sumedha !

Just wanted to know you have tried this with the tablet view as well right?

**Comment by 99sumedha** [comment]
@vasharma05 Yes 😊

**Comment by brandones** [comment]
> Hi @vasharma05, I'm still trying to get around the below error image

Please show the error in the dev console. Also try updating the `@openmrs/esm-framework` and `openmrs` dependencies (see [here](http://o3-dev.docs.openmrs.org/#/main/faq?id=im-not-seeing-the-latest-openmrsesm-framework-how-do-i-update-the-dependency)).

**Comment by 99sumedha** [comment]
Hi @brandones, thank you for checking out :). I got a fix from @manuelroemer to solve the error and now it's working

**Review by brandones — APPROVED** [review]

**Pull request merged**
