### PR TITLE
(test) O3-3361: E2E test that data isn't lost when opening a workspace from another workspace

### PR DESCRIPTION
**Pull request by chimanwadike**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR is an additional test steps in `clinical-forms.spec` to ensure form inputs are retained when navigating in and out of different workspaces.

## Related Issue

https://issues.openmrs.org/browse/O3-3361

### CODE REVIEW

**Review by jayasanka-sack — DISMISSED** [review]
Thanks for the PR, @chimanwadike! This should be implemented as a new test, as shown in the video provided in the [ticket](https://openmrs.atlassian.net/browse/O3-3361):

https://www.loom.com/share/d4b5f7bf310848e596193386707e8bb9

**Comment by chimanwadike** [comment]
Thanks @jayasanka-sack 
Going by the content of the video, I couldn't find the Clinical Encounter on any instance (both locally and pointing to dev3). However, available forms should be used I guess.

Regarding creating a new test for this. should this be a `workspace_spec` file or what are your thoughts about the filename, please?
  

> Thanks for the PR, @chimanwadike! This should be implemented as a new test, as shown in the video provided in the [ticket](https://openmrs.atlassian.net/browse/O3-3361):
> 
> https://www.loom.com/share/d4b5f7bf310848e596193386707e8bb9

**Comment by brandones** [comment]
@jayasanka-sack It doesn't matter to me what note it is, or what the data is. The important thing is that if I enter information on a workspace and then open another workspace from that one, the data I entered in the first workspace isn't lost when I go back to it.

**Review by brandones — APPROVED** [review]
LGTM

**Comment by jayasanka-sack** [comment]
Thanks for confirming @brandones !

**Comment by denniskigen** [comment]
This test is failing quite regularly in the CI environment. Can we review it when we get the chance?

**Comment by chimanwadike** [comment]
Will looking into it.
Thanks

**Pull request merged**
