### PR TITLE
O3-520 Add + Button to add active medications

### PR DESCRIPTION
**Pull request by kajambiya**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide).
- [x] My work includes tests or is validated by existing tests.

### CODE REVIEW

**Comment by kajambiya** [comment]
Added dummy data to be able to show the Add+ button. Also added form launcher to the Empty State

**Review by donaldkibet — CHANGES_REQUESTED** [review]
LGTM @kajambiya could you add unit test for this changes

**Comment by kajambiya** [comment]
> LGTM @kajambiya could you add unit test for this changes

Alright!

**Comment by donaldkibet** [comment]
@kajambiya please resolve the conflict

**Comment by kajambiya** [comment]
Closing PR to open a new one with the suggested changes

**Comment by kajambiya** [comment]
Closing PR to open a new one with the suggested changes

**Comment by brandones** [comment]
http://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=do-not-close-a-pr-and-recreate-a-new-one-with-the-same-code

**Comment by brandones** [comment]
Push new commits to update the code. Edit the description as needed. Add comments as needed. Do not open a new PR for the same work.

**Comment by kajambiya** [comment]
> Push new commits to update the code. Edit the description as needed. Add comments as needed. Do not open a new PR for the same work.

Thanks Brandon. Let me do that

**Comment by kajambiya** [comment]
Hello @donaldkibet I added unit test and resolved conflict accordingly.

**Pull request merged**
