### PR TITLE
(feat) Order basket UI tweaks

### PR DESCRIPTION
**Pull request by denniskigen**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-dev.docs.openmrs.org/#/getting_started/contributing?id=your-pr-title-should-indicate-the-type-of-change-it-is) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [x] My work includes tests or is validated by existing tests.

## Summary

This PR applies several tweaks to the order basket to get the UI elements to conform to new designs for the [order basket header](https://zeroheight.com/23a080e38/p/7456f7-order-basket-header) and [order items](https://zeroheight.com/23a080e38/p/030b9a-order-item).

### Before

CleanShot 2023-11-20 at 11  06 07@2x

CleanShot 2023-11-20 at 11  10 51@2x

CleanShot 2023-11-20 at 11  10 26@2x

### After

CleanShot 2023-11-20 at 11  09 16@2x

CleanShot 2023-11-20 at 11  09 37@2x

CleanShot 2023-11-20 at 11  09 58@2x

### CODE REVIEW

**Comment by denniskigen** [comment]
Is it preferable to just omit the medications details when they're not available instead of showing these empty dashes, @gracepotma @ibacher?

**Comment by ibacher** [comment]
@denniskigen My vote is for yes. With the caveat that I'd probably try to ensure that there's an em-dash between, e.g., DOSE and REFILLS.

**Review by ibacher — APPROVED** [review]

**Comment by denniskigen** [comment]
This is how things look with the change:

CleanShot 2023-11-20 at 11  43 15@2x

**Comment by ibacher** [comment]
That looks right to me!

**Pull request merged**
