### PR TITLE
(fix) O3-3622: Allow saving lab reference number with the lab order

### PR DESCRIPTION
**Pull request by vasharma05**
## Requirements

- [x] This PR has a title that briefly describes the work done including the ticket number. If there is a ticket, make sure your PR title includes a [conventional commit](https://o3-docs.openmrs.org/docs/frontend-modules/contributing.en-US#contributing-guidelines) label. See existing PR titles for inspiration.
- [x] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://om.rs/o3ui).
- [x] My work includes tests or is validated by existing tests.

## Summary
This PR allows saving Lab reference number in the 	`accessionNumber` property of the order.

## Screenshots

https://github.com/user-attachments/assets/a2349d32-6c4b-47ab-b178-f7160655b34f

## Related Issue
https://issues.openmrs.org/browse/O3-3622

### CODE REVIEW

**Comment by vasharma05** [comment]
@usamaidrsk , I have added the video recording, thanks!

**Comment by kdaud** [comment]
@denniskigen @usamaidrsk could you review this PR when you get a chance? Thanks!

**Review by usamaidrsk — APPROVED** [review]
Looks great.
Thanks for the work @vasharma05.

**Comment by denniskigen** [comment]
Any qualms with this approach? @dkayiwa @ibacher @mogoodrich?

**Comment by mogoodrich** [comment]
> Any qualms with this approach? @dkayiwa @ibacher @mogoodrich?

Thanks for copying me in, @denniskigen , sorry I haven't been following all this more closely.  Yes, the accession number field is the appropriate place to store a lab reference number... it does seem little odd that we would be collecting that at the time the order was placed (this would seem to be something entered in a fulfillment system?), but if we have a requirement I'm okay with it... maybe make whether it is a field on the order form configurable?

**Comment by denniskigen** [comment]
@vasharma05 do we also want to the change the input's label text from `Lab reference number` to `Accession number`?

**Comment by ibacher** [comment]
> do we also want to the change the input's label text from Lab reference number to Accession number?

I'm guessing the wording here was chosen in consultation with clinicians. In any case, I'd make that a separate issue if we want to change the form label.

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
